(() => {
  'use strict';
  const api=window.VisionLab,registry=window.VisionModels,loader=window.VisionModelLoader;
  if(!api||!registry||!loader||!window.ort)return;
  const $=id=>document.getElementById(id),TINY=registry.tinyyolo,YOLO=registry.yolox,RT=registry.rtdetr,COCO80=registry.labels.coco80,VOC20=registry.labels.voc20,VOC_CANON=registry.labels.vocCanonical;
  const state={image:null,running:false,benchmarking:false,tinyBuffer:null,tinySession:null,tinyProvider:'',tinyDownloadMs:NaN,tinyInitMs:NaN,tinyCacheState:'',tinySource:'',yoloBuffer:null,yoloSession:null,yoloProvider:'',yoloDownloadMs:NaN,yoloInitMs:NaN,yoloCacheState:'',yoloSource:'',rtPipe:null,rtBackend:'',rtDtype:'',rtLoadMs:NaN,rtCacheState:'',rtModule:null,lastHeadMaps:null,lastRun:{tiny:null,ssd:null,yolo:null,rt:null}};
  const report=(model,event)=>api.reportRuntimeEvent?.(model,event);
  const ms=api.ms,threshold=()=>api.getConfidence(),retainThreshold=()=>api.getRetentionThreshold?api.getRetentionThreshold():0.1,syncConfidence=()=>{$('race-confidence').textContent=threshold().toFixed(2)};syncConfidence();$('confidence').addEventListener('input',()=>{syncConfidence();redrawRaceResults();});
  const setStatus=(text,kind='')=>{const el=$('race-status');el.textContent=text;el.className=`status ${kind}`.trim()},sourceDims=s=>api.sourceSize(s),sleepFrame=()=>new Promise(requestAnimationFrame);
  const median=v=>{const a=[...v].sort((x,y)=>x-y),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2},percentile=(v,p)=>{const a=[...v].sort((x,y)=>x-y);return a[Math.max(0,Math.min(a.length-1,Math.ceil(p*a.length)-1))]},cv=v=>{const m=v.reduce((a,b)=>a+b,0)/v.length,q=v.reduce((s,x)=>s+(x-m)**2,0)/v.length;return m>0?Math.sqrt(q)/m*100:NaN};
  function updateProgress(prefix,info){const pct=Number.isFinite(info.percent)?Math.max(0,Math.min(100,info.percent)):null,bar=$(`${prefix}-progress-bar`),text=$(`${prefix}-progress-text`);if(bar)bar.style.width=pct===null?'18%':`${pct.toFixed(1)}%`;if(text){const loaded=loader.formatBytes(info.loaded),total=loader.formatBytes(info.total);text.textContent=pct===null?`${loaded} downloaded`:`${pct.toFixed(0)}% · ${loaded} / ${total}`}}
  loader.status(TINY).then(x=>$('race-tiny-cache').textContent=x.source?`${x.state} · ${x.source}`:x.state).catch(()=>{});
  async function getTinyBuffer(){if(state.tinyBuffer){report('tinyyolo',{type:'runtime',backend:state.tinyProvider,downloadMs:0,initMs:state.tinyInitMs,bytes:TINY.bytes,cacheState:'memory',source:state.tinySource});return state.tinyBuffer}const r=await loader.load(TINY,{onState:x=>{state.tinyCacheState=x.state;state.tinySource=x.source||state.tinySource;$('race-tiny-cache').textContent=x.source?`${x.state} · ${x.source}`:x.state;if(x.source)$('race-tiny-source').textContent=x.source;report('tinyyolo',{type:'cache',text:x.source?`${x.state} · ${x.source}`:x.state})},onProgress:x=>{updateProgress('race-tiny',x);report('tinyyolo',{type:'progress',info:x})}});state.tinyBuffer=r.buffer;state.tinyDownloadMs=r.downloadMs;state.tinyCacheState=r.cacheState;state.tinySource=r.source;$('race-tiny-source').textContent=r.source;$('race-tiny-cache').textContent=`${r.cacheState} · ${r.source}`;report('tinyyolo',{type:'runtime',backend:state.tinyProvider,downloadMs:r.downloadMs,bytes:r.buffer.byteLength,cacheState:r.cacheState,source:r.source});return r.buffer}
  async function createTinySession(force=''){if(state.tinySession&&(!force||state.tinyProvider===force)){report('tinyyolo',{type:'runtime',backend:state.tinyProvider,downloadMs:0,initMs:state.tinyInitMs,bytes:TINY.bytes,cacheState:'memory',source:state.tinySource});return state.tinySession;}const buffer=await getTinyBuffer(),providers=(force?[force]:TINY.executionProviders).filter(p=>p!=='webgpu'||navigator.gpu);let lastError;for(const provider of providers)try{setStatus(`Initializing Tiny YOLOv2 on ${provider.toUpperCase()}…`,'loading');const t=performance.now(),session=await ort.InferenceSession.create(buffer,{executionProviders:[provider],graphOptimizationLevel:'all'});state.tinyInitMs=performance.now()-t;if(state.tinySession&&state.tinySession!==session&&typeof state.tinySession.release==='function')try{await state.tinySession.release()}catch(_){}state.tinySession=session;state.tinyProvider=provider;$('race-tiny-backend').textContent=provider.toUpperCase();$('race-tiny-startup').textContent=`${ms(state.tinyDownloadMs)} / ${ms(state.tinyInitMs)}`;report('tinyyolo',{type:'runtime',backend:provider,downloadMs:state.tinyDownloadMs,initMs:state.tinyInitMs,bytes:TINY.bytes,cacheState:state.tinyCacheState,source:state.tinySource});return session}catch(err){lastError=err;console.warn('Tiny YOLOv2 provider failed',provider,err)}throw lastError||new Error('No compatible Tiny YOLOv2 execution provider.')}
  loader.status(YOLO).then(x=>$('race-yolo-cache').textContent=x.source?`${x.state} · ${x.source}`:x.state).catch(()=>{});
  async function getYoloBuffer(){if(state.yoloBuffer){report('yolox',{type:'runtime',backend:state.yoloProvider,downloadMs:0,initMs:state.yoloInitMs,bytes:YOLO.bytes,cacheState:'memory',source:state.yoloSource});return state.yoloBuffer}const r=await loader.load(YOLO,{onState:x=>{state.yoloCacheState=x.state;state.yoloSource=x.source||state.yoloSource;$('race-yolo-cache').textContent=x.source?`${x.state} · ${x.source}`:x.state;if(x.source)$('race-yolo-source').textContent=x.source;report('yolox',{type:'cache',text:x.source?`${x.state} · ${x.source}`:x.state})},onProgress:x=>{updateProgress('race-yolo',x);report('yolox',{type:'progress',info:x})}});state.yoloBuffer=r.buffer;state.yoloDownloadMs=r.downloadMs;state.yoloCacheState=r.cacheState;state.yoloSource=r.source;$('race-yolo-source').textContent=r.source;$('race-yolo-cache').textContent=`${r.cacheState} · ${r.source}`;report('yolox',{type:'runtime',backend:state.yoloProvider,downloadMs:r.downloadMs,bytes:r.buffer.byteLength,cacheState:r.cacheState,source:r.source});return r.buffer}
  async function createYoloSession(force=''){if(state.yoloSession&&(!force||state.yoloProvider===force)){report('yolox',{type:'runtime',backend:state.yoloProvider,downloadMs:0,initMs:state.yoloInitMs,bytes:YOLO.bytes,cacheState:'memory',source:state.yoloSource});return state.yoloSession;}const buffer=await getYoloBuffer(),providers=(force?[force]:YOLO.executionProviders).filter(p=>p!=='webgpu'||navigator.gpu);let lastError;for(const provider of providers)try{setStatus(`Initializing YOLOX on ${provider.toUpperCase()}…`,'loading');const t=performance.now(),session=await ort.InferenceSession.create(buffer,{executionProviders:[provider],graphOptimizationLevel:'all'});state.yoloInitMs=performance.now()-t;if(state.yoloSession&&state.yoloSession!==session&&typeof state.yoloSession.release==='function')try{await state.yoloSession.release()}catch(_){}state.yoloSession=session;state.yoloProvider=provider;$('race-yolo-backend').textContent=provider.toUpperCase();$('race-yolo-startup').textContent=`${ms(state.yoloDownloadMs)} / ${ms(state.yoloInitMs)}`;report('yolox',{type:'runtime',backend:provider,downloadMs:state.yoloDownloadMs,initMs:state.yoloInitMs,bytes:YOLO.bytes,cacheState:state.yoloCacheState,source:state.yoloSource});return session}catch(err){lastError=err;console.warn('YOLOX provider failed',provider,err)}throw lastError||new Error('No compatible YOLOX execution provider.')}
  function prepareDisplay(source,canvas){const {w,h}=sourceDims(source),scale=Math.min(1,640/Math.max(w,h));canvas.width=Math.max(1,Math.round(w*scale));canvas.height=Math.max(1,Math.round(h*scale));canvas.getContext('2d').drawImage(source,0,0,canvas.width,canvas.height)}
  function prepareTiny(source,canvas){const {w,h}=sourceDims(source),size=TINY.input;if(!w||!h)throw new Error('Race image has no readable dimensions.');const work=$('race-tiny-work');work.width=size;work.height=size;const ctx=work.getContext('2d',{willReadFrequently:true});ctx.drawImage(source,0,0,size,size);const rgba=ctx.getImageData(0,0,size,size).data,plane=size*size,chw=new Float32Array(plane*3);for(let p=0,s=0;p<plane;p++,s+=4){chw[p]=rgba[s];chw[plane+p]=rgba[s+1];chw[plane*2+p]=rgba[s+2]}prepareDisplay(source,canvas);return{tensor:new ort.Tensor('float32',chw,[1,3,size,size]),w,h}}
  async function runTinySession(session,tensor){const run=s=>s.run({[s.inputNames[0]]:tensor});try{return await run(session)}catch(err){if(state.tinyProvider!=='webgpu')throw err;console.warn('Tiny YOLOv2 WebGPU run failed; retrying WASM',err);const old=state.tinySession;state.tinySession=null;state.tinyProvider='';if(old&&typeof old.release==='function')try{await old.release()}catch(_){}return run(await createTinySession('wasm'))}}
  function prepareYolo(source,canvas){const {w,h}=sourceDims(source),size=YOLO.input;if(!w||!h)throw new Error('Race image has no readable dimensions.');const ratio=Math.min(size/h,size/w),rw=Math.max(1,Math.floor(w*ratio)),rh=Math.max(1,Math.floor(h*ratio)),work=$('race-yolo-work');work.width=size;work.height=size;const ctx=work.getContext('2d',{willReadFrequently:true});ctx.fillStyle='rgb(114,114,114)';ctx.fillRect(0,0,size,size);ctx.drawImage(source,0,0,rw,rh);const rgba=ctx.getImageData(0,0,size,size).data,plane=size*size,chw=new Float32Array(plane*3);for(let p=0,s=0;p<plane;p++,s+=4){chw[p]=rgba[s+2];chw[plane+p]=rgba[s+1];chw[plane*2+p]=rgba[s]}prepareDisplay(source,canvas);return{tensor:new ort.Tensor('float32',chw,[1,3,size,size]),ratio,w,h}}
  async function runYoloSession(session,tensor){const run=s=>s.run({[s.inputNames[0]]:tensor});try{return await run(session)}catch(err){if(state.yoloProvider!=='webgpu')throw err;console.warn('YOLOX WebGPU run failed; retrying WASM',err);const old=state.yoloSession;state.yoloSession=null;state.yoloProvider='';if(old&&typeof old.release==='function')try{await old.release()}catch(_){}return run(await createYoloSession('wasm'))}}
  function iou(a,b){const t=Math.max(a[0],b[0]),l=Math.max(a[1],b[1]),bt=Math.min(a[2],b[2]),r=Math.min(a[3],b[3]),inter=Math.max(0,bt-t)*Math.max(0,r-l),aa=Math.max(0,a[2]-a[0])*Math.max(0,a[3]-a[1]),bb=Math.max(0,b[2]-b[0])*Math.max(0,b[3]-b[1]),u=aa+bb-inter;return u>0?inter/u:0}
  const sigmoid=x=>1/(1+Math.exp(-Math.max(-60,Math.min(60,x))));
  function decodeTiny(output){const data=output&&output.data;if(!data||data.length!==125*13*13)throw new Error(`Unexpected Tiny YOLOv2 output: ${data?data.length:0} values; expected ${125*13*13}.`);const grid=13,attrs=25,anchors=TINY.anchors,candidates=[],at=(channel,y,x)=>Number(data[(channel*grid+y)*grid+x]);for(let gy=0;gy<grid;gy++)for(let gx=0;gx<grid;gx++)for(let b=0;b<5;b++){const ch=b*attrs,tx=at(ch,gy,gx),ty=at(ch+1,gy,gx),tw=Math.max(-20,Math.min(20,at(ch+2,gy,gx))),th=Math.max(-20,Math.min(20,at(ch+3,gy,gx))),obj=sigmoid(at(ch+4,gy,gx));let maxLogit=-Infinity;for(let c=0;c<20;c++)maxLogit=Math.max(maxLogit,at(ch+5+c,gy,gx));let sum=0,best=-1,bestExp=-Infinity;for(let c=0;c<20;c++){const e=Math.exp(at(ch+5+c,gy,gx)-maxLogit);sum+=e;if(e>bestExp){bestExp=e;best=c}}const classProb=sum>0?bestExp/sum:0,score=obj*classProb;if(score<retainThreshold())continue;const cx=(gx+sigmoid(tx))/grid,cy=(gy+sigmoid(ty))/grid,bw=Math.exp(tw)*anchors[b*2]/grid,bh=Math.exp(th)*anchors[b*2+1]/grid,top=Math.max(0,cy-bh/2),left=Math.max(0,cx-bw/2),bottom=Math.min(1,cy+bh/2),right=Math.min(1,cx+bw/2);if(bottom>top&&right>left)candidates.push({score,classId:best,sourceLabel:VOC20[best],label:VOC_CANON[best],box:[top,left,bottom,right]})}candidates.sort((a,b)=>b.score-a.score);const kept=[];for(const d of candidates){if(kept.every(k=>k.label!==d.label||iou(d.box,k.box)<=TINY.nms))kept.push(d);if(kept.length>=100)break}return kept}
  async function runTiny(source,canvas){const session=await createTinySession(),ts=performance.now(),ps=performance.now(),prep=prepareTiny(source,canvas),preMs=performance.now()-ps,is=performance.now(),results=await runTinySession(session,prep.tensor),infMs=performance.now()-is,post=performance.now(),output=results[session.outputNames[0]]||results[Object.keys(results)[0]],detections=decodeTiny(output),visible=api.drawDetections(canvas,detections),postMs=performance.now()-post;return{preMs,infMs,postMs,totalMs:performance.now()-ts,detections,visible,width:TINY.input,height:TINY.input,retained:detections.length,retentionThreshold:retainThreshold(),timingBoundary:'onnx-run'}}
  function renderHeadMaps(maps){for(const head of maps){const canvas=$(`feature-s${head.stride}`);if(!canvas)continue;const ctx=canvas.getContext('2d'),img=ctx.createImageData(head.grid,head.grid);let max=0;for(const v of head.data)if(Number.isFinite(v)&&v>max)max=v;const d=max||1;for(let i=0;i<head.data.length;i++){const v=Math.max(0,Math.min(1,head.data[i]/d)),o=i*4;img.data[o]=Math.round(28+v*210);img.data[o+1]=Math.round(48+v*160);img.data[o+2]=Math.round(42+v*70);img.data[o+3]=255}const tiny=document.createElement('canvas');tiny.width=head.grid;tiny.height=head.grid;tiny.getContext('2d').putImageData(img,0,0);ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(tiny,0,0,canvas.width,canvas.height)}const s=$('feature-map-status');if(s)s.textContent='Live from last YOLOX inference'}
  function decodeYolo(output,ratio,w,h,renderFeatures=true){const data=output.data,attrs=85,expected=52*52+26*26+13*13,rows=Math.floor(data.length/attrs);if(rows!==expected)throw new Error(`Unexpected YOLOX output: ${rows} rows; expected ${expected}.`);const candidates=[],maps=[];let row=0;for(const stride of[8,16,32]){const grid=YOLO.input/stride,map=new Float32Array(grid*grid);let mi=0;for(let gy=0;gy<grid;gy++)for(let gx=0;gx<grid;gx++,row++,mi++){const o=row*attrs,obj=Number(data[o+4]);map[mi]=obj;let cls=0,cp=-Infinity;for(let c=0;c<80;c++){const p=Number(data[o+5+c]);if(p>cp){cp=p;cls=c}}const score=obj*cp;if(score<retainThreshold())continue;const cx=(Number(data[o])+gx)*stride,cy=(Number(data[o+1])+gy)*stride,bw=Math.exp(Number(data[o+2]))*stride,bh=Math.exp(Number(data[o+3]))*stride,x1=Math.max(0,(cx-bw/2)/ratio),y1=Math.max(0,(cy-bh/2)/ratio),x2=Math.min(w,(cx+bw/2)/ratio),y2=Math.min(h,(cy+bh/2)/ratio);if(x2>x1&&y2>y1)candidates.push({score,classId:cls,label:COCO80[cls],box:[y1/h,x1/w,y2/h,x2/w]})}maps.push({stride,grid,data:map})}candidates.sort((a,b)=>b.score-a.score);const kept=[];for(const d of candidates){if(kept.every(k=>iou(d.box,k.box)<=YOLO.nms))kept.push(d);if(kept.length>=100)break}state.lastHeadMaps=maps;if(renderFeatures&&!state.benchmarking)renderHeadMaps(maps);return kept}
  async function runYolo(source,canvas,{renderFeatures=true}={}){const session=await createYoloSession(),ts=performance.now(),ps=performance.now(),prep=prepareYolo(source,canvas),preMs=performance.now()-ps,is=performance.now(),results=await runYoloSession(session,prep.tensor),infMs=performance.now()-is,post=performance.now(),output=results[session.outputNames[0]]||results[Object.keys(results)[0]],detections=decodeYolo(output,prep.ratio,prep.w,prep.h,renderFeatures),visible=api.drawDetections(canvas,detections),postMs=performance.now()-post;return{preMs,infMs,postMs,totalMs:performance.now()-ts,detections,visible,width:YOLO.input,height:YOLO.input,retained:detections.length,retentionThreshold:retainThreshold()}}
  async function importTransformers(){if(state.rtModule)return state.rtModule;setStatus(`Loading pinned Transformers.js ${registry.runtime.transformersJs} runtime…`,'loading');state.rtModule=await import(registry.runtime.transformersJsUrl);state.rtModule.env.allowLocalModels=false;if('useWasmCache' in state.rtModule.env)state.rtModule.env.useWasmCache=true;return state.rtModule}
  async function rtCached(mod,device,dtype){try{if(mod.ModelRegistry&&typeof mod.ModelRegistry.is_pipeline_cached==='function')return await mod.ModelRegistry.is_pipeline_cached(RT.task,RT.modelId,{revision:RT.revision,device,dtype});if('caches'in window){for(const name of await caches.keys()){const cache=await caches.open(name),keys=await cache.keys();if(keys.some(r=>r.url.includes(RT.modelId)))return true}}}catch(_){}return false}
  function rtProgress(info){const bar=$('race-rt-progress-bar'),text=$('race-rt-progress-text');let pct=Number(info&&info.progress);if(Number.isFinite(pct)&&pct<=1)pct*=100;if(Number.isFinite(pct))bar.style.width=`${Math.max(0,Math.min(100,pct)).toFixed(1)}%`;const file=info&&info.file?String(info.file).split('/').pop():'model files',loaded=Number(info&&info.loaded),total=Number(info&&info.total);if(Number.isFinite(loaded)&&Number.isFinite(total)&&total>0)text.textContent=`${file} · ${(loaded/total*100).toFixed(0)}% · ${loader.formatBytes(loaded)} / ${loader.formatBytes(total)}`;else if(info&&info.status)text.textContent=`${info.status} · ${file}`;report('rtdetr',{type:'progress',info:{percent:Number.isFinite(pct)?pct:undefined,loaded,total}})}
  async function createRT(force=''){if(state.rtPipe&&(!force||state.rtBackend===force)){const cfg=RT.runtime[state.rtBackend]||{};report('rtdetr',{type:'runtime',backend:state.rtBackend,dtype:state.rtDtype,initMs:state.rtLoadMs,bytes:cfg.modelBytes,cacheState:'memory',source:`HF pinned ${RT.revision}`});return state.rtPipe;}const mod=await importTransformers(),attempts=force?[RT.runtime[force]]:(navigator.gpu?[RT.runtime.webgpu,RT.runtime.wasm]:[RT.runtime.wasm]);let lastError;for(const cfg of attempts)try{const cached=await rtCached(mod,cfg.device,cfg.dtype);$('race-rt-cache').textContent=cached?'browser cache':'network/cache miss';$('race-rt-backend').textContent=cfg.device.toUpperCase();$('race-rt-asset').textContent=`${cfg.dtype} · ~${loader.formatBytes(cfg.modelBytes)}`;setStatus(`Loading RT-DETR R18 on ${cfg.device.toUpperCase()} (${cfg.dtype})…`,'loading');const t=performance.now(),pipe=await mod.pipeline(RT.task,RT.modelId,{device:cfg.device,dtype:cfg.dtype,revision:RT.revision,progress_callback:rtProgress});state.rtLoadMs=performance.now()-t;state.rtPipe=pipe;state.rtBackend=cfg.device;state.rtDtype=cfg.dtype;state.rtCacheState=cached?'browser cache':'cached after load';$('race-rt-load').textContent=ms(state.rtLoadMs);$('race-rt-cache').textContent=state.rtCacheState;$('race-rt-progress-bar').style.width='100%';$('race-rt-progress-text').textContent='Ready';report('rtdetr',{type:'runtime',backend:cfg.device,dtype:cfg.dtype,initMs:state.rtLoadMs,bytes:cfg.modelBytes,cacheState:state.rtCacheState,source:`HF pinned ${RT.revision}`});return pipe}catch(err){lastError=err;console.warn('RT-DETR load attempt failed',cfg,err);state.rtPipe=null}throw lastError||new Error('RT-DETR could not be loaded.')}
  async function runRT(source,canvas){
    let pipe=await createRT();
    const {w,h}=sourceDims(source),work=$('race-rt-work');work.width=w;work.height=h;work.getContext('2d').drawImage(source,0,0,w,h);
    let output,infMs;
    try{const t=performance.now();output=await pipe(work,{threshold:retainThreshold()});infMs=performance.now()-t;}
    catch(err){
      if(state.rtBackend!=='webgpu')throw err;
      console.warn('RT-DETR WebGPU inference failed; retrying WASM q8',err);
      if(state.rtPipe&&typeof state.rtPipe.dispose==='function')try{await state.rtPipe.dispose()}catch(_){}
      state.rtPipe=null;state.rtBackend='';state.rtDtype='';
      pipe=await createRT('wasm');const t=performance.now();output=await pipe(work,{threshold:retainThreshold()});infMs=performance.now()-t;
    }
    const list=Array.isArray(output)&&Array.isArray(output[0])?output[0]:output,raw=Array.isArray(list)?list:[],clamp=v=>Math.max(0,Math.min(1,v));
    const detections=raw.map(x=>({score:Number(x.score),label:String(x.label),classId:-1,box:[Number(x.box?.ymin)/h,Number(x.box?.xmin)/w,Number(x.box?.ymax)/h,Number(x.box?.xmax)/w]})).filter(x=>Number.isFinite(x.score)&&x.box.every(Number.isFinite)).map(x=>({...x,box:x.box.map(clamp)})).filter(x=>x.box[2]>x.box[0]&&x.box[3]>x.box[1]);
    const droppedInvalid=raw.length-detections.length;prepareDisplay(source,canvas);const p=performance.now(),visible=api.drawDetections(canvas,detections),postMs=performance.now()-p;
    return{preMs:NaN,infMs,postMs,totalMs:infMs+postMs,detections,visible,width:RT.input,height:RT.input,timingBoundary:'transformers-pipeline',rawCount:raw.length,retained:detections.length,droppedInvalid,retentionThreshold:retainThreshold()};
  }
  const visible=d=>d.filter(x=>x.score>=threshold());
  function compare(a,b){const aa=visible(a),bb=visible(b),used=new Set();let both=0;for(const old of aa){let best=-1,bi=0;for(let i=0;i<bb.length;i++){if(used.has(i)||bb[i].label!==old.label)continue;const v=iou(old.box,bb[i].box);if(v>=.35&&v>bi){best=i;bi=v}}if(best>=0){used.add(best);both++}}return{both,aOnly:aa.length-both,bOnly:bb.length-both}}
  function hasMatch(det,list){return list.some(other=>other.label===det.label&&iou(det.box,other.box)>=.35)}
  function updateOverlap(){const t=state.lastRun.tiny?.detections,s=state.lastRun.ssd?.detections,y=state.lastRun.yolo?.detections,r=state.lastRun.rt?.detections;if(!t||!s||!y||!r)return;const tv=visible(t),sv=visible(s),yv=visible(y),rv=visible(r);$('race-match-tiny-ssd').textContent=String(compare(t,s).both);$('race-match-tiny-yolo').textContent=String(compare(t,y).both);$('race-match-tiny-rt').textContent=String(compare(t,r).both);$('race-match-ssd-yolo').textContent=String(compare(s,y).both);$('race-match-ssd-rt').textContent=String(compare(s,r).both);$('race-match-yolo-rt').textContent=String(compare(y,r).both);$('race-only-tiny').textContent=String(tv.filter(d=>!hasMatch(d,sv)&&!hasMatch(d,yv)&&!hasMatch(d,rv)).length);$('race-only-ssd').textContent=String(sv.filter(d=>!hasMatch(d,tv)&&!hasMatch(d,yv)&&!hasMatch(d,rv)).length);$('race-only-yolo').textContent=String(yv.filter(d=>!hasMatch(d,tv)&&!hasMatch(d,sv)&&!hasMatch(d,rv)).length);$('race-only-rt').textContent=String(rv.filter(d=>!hasMatch(d,tv)&&!hasMatch(d,sv)&&!hasMatch(d,yv)).length);}
  function redrawRaceResults(){if(!state.image||state.running||state.benchmarking)return;let redrawn=false;for(const pair of [['tiny','tiny'],['ssd','ssd'],['yolo','yolo'],['rt','rt']]){const key=pair[0],slot=pair[1],run=state.lastRun[key];if(!run)continue;const canvas=$('race-'+slot+'-canvas');prepareDisplay(state.image,canvas);run.visible=api.drawDetections(canvas,run.detections);$('race-'+slot+'-count').textContent=String(run.visible);redrawn=true}if(redrawn){updateOverlap();setStatus('Confidence '+threshold().toFixed(2)+' applied to retained race outputs without new inference.')}}
  function useImage(img,label){state.image=img;state.lastRun={tiny:null,ssd:null,yolo:null,rt:null};$('race-run').disabled=false;$('race-benchmark').disabled=true;for(const k of['tiny','ssd','yolo','rt']){$('race-'+k+'-empty').hidden=false;$('race-'+k+'-canvas').hidden=true}for(const id of['race-tiny-inf','race-tiny-total','race-tiny-count','race-ssd-inf','race-ssd-total','race-ssd-count','race-yolo-inf','race-yolo-total','race-yolo-count','race-rt-inf','race-rt-total','race-rt-count','race-rt-retained','race-rt-invalid','race-match-tiny-ssd','race-match-tiny-yolo','race-match-tiny-rt','race-match-ssd-yolo','race-match-ssd-rt','race-match-yolo-rt','race-only-tiny','race-only-ssd','race-only-yolo','race-only-rt','rb-tiny-backend','rb-tiny-p50','rb-tiny-p90','rb-tiny-total','rb-tiny-cv','rb-ssd-backend','rb-ssd-p50','rb-ssd-p90','rb-ssd-total','rb-ssd-cv','rb-yolo-backend','rb-yolo-p50','rb-yolo-p90','rb-yolo-total','rb-yolo-cv','rb-rt-backend','rb-rt-p50','rb-rt-p90','rb-rt-total','rb-rt-cv'])$(id).textContent='—';$('race-ssd-input').textContent='dynamic ≤640';$('race-benchmark-note').textContent='Not benchmarked yet.';setStatus(label+' ready. Run four generations with confidence '+threshold().toFixed(2)+'.')}
  $('race-image-file').addEventListener('change',e=>{const file=e.target.files&&e.target.files[0];if(!file)return;if(!file.type.startsWith('image/')){setStatus('Please choose an image file.','error');return}const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{URL.revokeObjectURL(url);useImage(img,file.name||'Race image')};img.onerror=()=>{URL.revokeObjectURL(url);setStatus('The selected race image could not be decoded.','error')};img.src=url});
  $('race-use-current').addEventListener('click',()=>{const img=api.getImage();if(!img){setStatus('No Time Machine image is loaded yet.','error');return}useImage(img,'Time Machine image')});
  async function runRace(){if(!state.image||state.running)return;state.running=true;const image=state.image;$('race-image-file').disabled=true;$('confidence').disabled=true;$('race-run').disabled=true;$('race-benchmark').disabled=true;$('race-use-current').disabled=true;syncConfidence();try{
    setStatus('Running Tiny YOLOv2 (2016)… first load is ~63.5 MB.','loading');const tiny=await runTiny(image,$('race-tiny-canvas'));state.lastRun.tiny=tiny;$('race-tiny-empty').hidden=true;$('race-tiny-canvas').hidden=false;$('race-tiny-inf').textContent=ms(tiny.infMs);$('race-tiny-total').textContent=ms(tiny.totalMs);$('race-tiny-count').textContent=String(tiny.visible);
    setStatus('Running SSD-MobileNet baseline…','loading');const ssd=await api.runBaseline(image,$('race-ssd-canvas'));state.lastRun.ssd=ssd;$('race-ssd-empty').hidden=true;$('race-ssd-canvas').hidden=false;$('race-ssd-backend').textContent=(api.getBaselineProvider()||'WASM').toUpperCase();$('race-ssd-input').textContent=ssd.width+'×'+ssd.height;$('race-ssd-inf').textContent=ms(ssd.infMs);$('race-ssd-total').textContent=ms(ssd.totalMs);$('race-ssd-count').textContent=String(ssd.visible);
    setStatus('Running YOLOX-Nano…','loading');const yolo=await runYolo(image,$('race-yolo-canvas'));state.lastRun.yolo=yolo;$('race-yolo-empty').hidden=true;$('race-yolo-canvas').hidden=false;$('race-yolo-inf').textContent=ms(yolo.infMs);$('race-yolo-total').textContent=ms(yolo.totalMs);$('race-yolo-count').textContent=String(yolo.visible);
    setStatus('Running RT-DETR R18… first load may download 20–40 MB.','loading');const rt=await runRT(image,$('race-rt-canvas'));state.lastRun.rt=rt;$('race-rt-empty').hidden=true;$('race-rt-canvas').hidden=false;$('race-rt-inf').textContent=ms(rt.infMs);$('race-rt-total').textContent=ms(rt.totalMs);$('race-rt-count').textContent=String(rt.visible);$('race-rt-retained').textContent=rt.retained+' @ ≥'+rt.retentionThreshold.toFixed(2);$('race-rt-invalid').textContent=String(rt.droppedInvalid);
    updateOverlap();setStatus('Race complete: Tiny YOLOv2 '+tiny.visible+', SSD '+ssd.visible+', YOLOX '+yolo.visible+', RT-DETR '+rt.visible+'. Pairwise overlap is shown below.');$('race-benchmark').disabled=false;
  }catch(err){console.error(err);setStatus(err&&err.message?err.message:String(err),'error')}finally{state.running=false;$('race-image-file').disabled=false;$('confidence').disabled=false;$('race-run').disabled=!state.image;$('race-use-current').disabled=false}}
  $('race-run').addEventListener('click',runRace);
  async function runModel(model,source,canvas,{benchmarking=false}={}){if(model==='tinyyolo')return runTiny(source,canvas);if(model==='ssd')return api.runBaseline(source,canvas);if(model==='yolox')return runYolo(source,canvas,{renderFeatures:!benchmarking});if(model==='rtdetr')return runRT(source,canvas);throw new Error(`Unknown runnable model: ${model}`)}
  function getRuntimeInfo(model){if(model==='tinyyolo')return{backend:state.tinyProvider,downloadMs:state.tinyDownloadMs,initMs:state.tinyInitMs,bytes:TINY.bytes,cacheState:state.tinyCacheState,source:state.tinySource};if(model==='ssd')return{backend:api.getBaselineProvider()||'wasm'};if(model==='yolox')return{backend:state.yoloProvider,downloadMs:state.yoloDownloadMs,initMs:state.yoloInitMs,bytes:YOLO.bytes,cacheState:state.yoloCacheState,source:state.yoloSource};if(model==='rtdetr'){const cfg=RT.runtime[state.rtBackend]||{};return{backend:state.rtBackend,dtype:state.rtDtype,initMs:state.rtLoadMs,bytes:cfg.modelBytes,cacheState:state.rtCacheState,source:`HF pinned ${RT.revision}`}}return{}}
  function setBench(prefix,backend,samples){const inf=samples.map(x=>x.infMs),tot=samples.map(x=>x.totalMs);$(`rb-${prefix}-backend`).textContent=backend;$(`rb-${prefix}-p50`).textContent=ms(median(inf));$(`rb-${prefix}-p90`).textContent=ms(percentile(inf,.9));$(`rb-${prefix}-total`).textContent=ms(median(tot));$(`rb-${prefix}-cv`).textContent=`${cv(inf).toFixed(1)}%`}
  async function benchmarkRace(){if(!state.image||state.benchmarking)return;state.benchmarking=true;const image=state.image;$('race-image-file').disabled=true;$('race-use-current').disabled=true;$('confidence').disabled=true;$('race-benchmark').disabled=true;$('race-run').disabled=true;const runs=20,hidden=document.createElement('canvas');try{for(const spec of[
    {key:'tiny',label:'Tiny YOLOv2',backend:()=>state.tinyProvider.toUpperCase(),run:()=>runTiny(image,hidden)},
    {key:'ssd',label:'SSD-MobileNet',backend:()=>(api.getBaselineProvider()||'wasm').toUpperCase(),run:()=>api.runBaseline(image,hidden)},
    {key:'yolo',label:'YOLOX-Nano',backend:()=>state.yoloProvider.toUpperCase(),run:()=>runYolo(image,hidden,{renderFeatures:false})},
    {key:'rt',label:'RT-DETR R18',backend:()=>state.rtBackend.toUpperCase()+' '+state.rtDtype,run:()=>runRT(image,hidden)}
  ]){const samples=[];for(let i=0;i<runs;i++){$('race-benchmark-note').textContent=spec.label+': '+(i+1)+'/'+runs+' warm runs…';samples.push(await spec.run());await sleepFrame()}setBench(spec.key,spec.backend(),samples)}$('race-benchmark-note').textContent='20 sequential warm runs per model complete. Source image and UI confidence were locked. RT-DETR p50/p90 measures its Transformers.js object-detection pipeline call; Tiny YOLOv2/SSD/YOLOX isolate ORT model execution.';setStatus('Four-generation warm benchmark complete.')}catch(err){console.error(err);$('race-benchmark-note').textContent='Benchmark failed: '+(err.message||err);setStatus(err.message||String(err),'error')}finally{state.benchmarking=false;$('race-image-file').disabled=false;$('race-use-current').disabled=false;$('confidence').disabled=false;$('race-benchmark').disabled=false;$('race-run').disabled=false}}
  $('race-benchmark').addEventListener('click',benchmarkRace);
  window.VisionRace=Object.freeze({runRace,benchmarkRace,runModel,getRuntimeInfo,getHeadMaps:()=>state.lastHeadMaps,getRTBackend:()=>state.rtBackend});
})();