(() => {
  'use strict';
  const api=window.VisionLab,registry=window.VisionModels,loader=window.VisionModelLoader;
  if(!api||!registry||!loader||!window.ort)return;
  const $=id=>document.getElementById(id),TINY=registry.tinyyolo,YOLO=registry.yolox,RT=registry.rtdetr,COCO80=registry.labels.coco80,VOC20=registry.labels.voc20,VOC_CANON=registry.labels.vocCanonical;
  const DIAG_MODE=new URLSearchParams(location.search).get('diag')||'',DIAG=DIAG_MODE==='1'||DIAG_MODE==='2',BLACKBOX=DIAG_MODE==='2',DIAG_KEY='vel:race-diag-v1',BB_KEY='vel:race-diag-blackbox-v1',BB_JOURNAL_KEY='vel:race-diag-journal-v1',BB_SELECTION_KEY='vel:race-diag-selection-v1',BB_SETTLE_KEY='vel:race-diag-settle-v1',BB_BACKEND_KEY='vel:race-diag-backends-v1',BB_ATTEMPT_KEY='vel:race-diag-attempt-v1',BB_MATRIX_KEY='vel:race-diag-matrix-v1';
  let bbStage='page-ready',bbPrevious=null,bbEvents=[],bbPlan=[],bbBackendPlan={},bbAttempt=Number(readLocal(BB_ATTEMPT_KEY,0))||0,bbMatrix=readLocal(BB_MATRIX_KEY,null),bbBenchmarkDoneWall=0,bbLastBeat=performance.now(),bbMaxGap=0,bbLastLifecycle='page-init',bbOrderlyExit=false,bbSettleMs=0,matrixRunning=false,matrixStopRequested=false;
  const bbResident={},MATRIX_CASES=[{id:'A',label:'all-WASM',backends:{yolox:'wasm',rtdetr:'wasm'}},{id:'B',label:'YOLOX WebGPU · RT WASM q8',backends:{yolox:'webgpu',rtdetr:'wasm'}},{id:'C',label:'YOLOX WASM · RT WebGPU fp16',backends:{yolox:'wasm',rtdetr:'webgpu'}},{id:'D',label:'YOLOX WebGPU · RT WebGPU fp16',backends:{yolox:'webgpu',rtdetr:'webgpu'}}],MATRIX_ATTEMPTS=10;
  function readLocal(key,fallback=null){try{const v=JSON.parse(localStorage.getItem(key)||'null');return v??fallback}catch(_){return fallback}}
  function writeLocal(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true}catch(_){return false}}
  function readDiag(){if(!DIAG)return null;try{return JSON.parse(sessionStorage.getItem(DIAG_KEY)||'null')}catch(_){return null}}
  function showDiag(message){if(!DIAG)return;const el=$('race-diag-status');if(el){el.hidden=false;el.textContent=message}}
  function bbNavType(){const n=performance.getEntriesByType?.('navigation')?.[0];return n?.type||'unknown'}
  function bbMemory(){const m=performance.memory;return m&&Number.isFinite(m.usedJSHeapSize)?(m.usedJSHeapSize/1048576).toFixed(1)+' MB JS heap':'N/A'}
  function bbWorkCanvases(){const parts=[];for(const spec of getRaceSpecs(null,null,{benchmarking:true})){if(!spec.workCanvasId)continue;const c=$(spec.workCanvasId);if(c)parts.push(`${spec.label} ${c.width}×${c.height}`)}return parts.length?parts.join(' · '):'—'}
  function diagModelLabel(key){return getRaceSpecs(null,null,{benchmarking:true}).find(x=>x.key===key)?.label||key}
  function bbResidentText(value){const entries=Object.entries(value||{});return entries.length?entries.map(([key,on])=>`${diagModelLabel(key)} ${on?'ON':'OFF'}`).join(' · '):'none'}
  function bbBackendPlanText(value){const entries=Object.entries(value||{});return entries.length?entries.map(([key,mode])=>`${diagModelLabel(key)} ${mode}`).join(' · '):'auto'}
  function bbBackendText(){const parts=[];for(const spec of getRaceSpecs(null,null,{benchmarking:true})){const value=String(spec.backend?.()||'').trim();if(value)parts.push(`${spec.label} ${value}`)}return parts.length?parts.join(' · '):'—'}
  function bbMatrixText(value){if(!value)return'idle';if(value.phase==='complete')return`complete · A–D ×${value.attemptsPerCase||MATRIX_ATTEMPTS}`;const c=MATRIX_CASES[value.caseIndex]||MATRIX_CASES.find(x=>x.id===value.currentCase),attempt=value.currentAttempt||((value.completedInCase||0)+1),suffix=c?`${c.id} ${Math.min(attempt,value.attemptsPerCase||MATRIX_ATTEMPTS)}/${value.attemptsPerCase||MATRIX_ATTEMPTS} · ${c.label}`:'done';return`${value.phase||'ready'} · ${suffix}`}
  function bbJournal(event,extra={}){if(!BLACKBOX)return;bbEvents=[...bbEvents,{at:new Date().toISOString(),event,...extra}].slice(-40);writeLocal(BB_JOURNAL_KEY,bbEvents)}
  function bbSnapshot(){return{stage:bbStage,attempt:bbAttempt,matrix:bbMatrix?{...bbMatrix}:null,heartbeatAt:new Date().toISOString(),secondsSinceBenchmark:bbBenchmarkDoneWall?Math.max(0,(Date.now()-bbBenchmarkDoneWall)/1000):null,maxEventLoopGapMs:Math.round(bbMaxGap),lastLifecycle:bbLastLifecycle,orderlyExit:bbOrderlyExit,navigationType:bbNavType(),plan:[...bbPlan],settleMs:bbSettleMs,backendPlan:{...bbBackendPlan},backends:bbBackendText(),resident:{...bbResident},workCanvases:bbWorkCanvases(),memory:bbMemory()}}
  function renderBlackbox(){if(!BLACKBOX)return;const el=$('race-diag-blackbox');if(!el)return;el.hidden=false;const now=bbSnapshot(),prev=bbPrevious,tail=bbEvents.slice(-12).map(x=>x.at.slice(11,19)+'  '+x.event+(x.ms?(' · '+x.ms+' ms'):'')).join('\n'),plan=x=>(x&&x.length?x.map(diagModelLabel).join(' → '):'—');el.textContent=`DIAGNOSTIC BLACK BOX · diag=2
CURRENT
stage: ${now.stage}
attempt: ${now.attempt}
matrix: ${bbMatrixText(now.matrix)}
plan: ${plan(now.plan)}
inter-model settle: ${now.settleMs} ms
backend probes: ${bbBackendPlanText(now.backendPlan)}
actual backends: ${now.backends}
heartbeat: ${now.heartbeatAt}
since benchmark: ${now.secondsSinceBenchmark===null?'—':now.secondsSinceBenchmark.toFixed(1)+' s'}
event-loop max gap: ${now.maxEventLoopGapMs} ms
lifecycle: ${now.lastLifecycle} · orderly pagehide: ${now.orderlyExit?'yes':'no'}
navigation: ${now.navigationType}
resident: ${bbResidentText(now.resident)}
work canvases: ${now.workCanvases} · memory: ${now.memory}

PREVIOUS
${prev?`stage: ${prev.stage||'unknown'}
attempt: ${prev.attempt??0}
matrix: ${bbMatrixText(prev.matrix)}
plan: ${plan(prev.plan)}
inter-model settle: ${prev.settleMs??0} ms
backend probes: ${bbBackendPlanText(prev.backendPlan)}
actual backends: ${prev.backends||'—'}
last heartbeat: ${prev.heartbeatAt||'—'}
since benchmark: ${Number.isFinite(prev.secondsSinceBenchmark)?prev.secondsSinceBenchmark.toFixed(1)+' s':'—'}
event-loop max gap: ${prev.maxEventLoopGapMs??'—'} ms
lifecycle: ${prev.lastLifecycle||'—'} · orderly pagehide: ${prev.orderlyExit?'yes':'no'}
navigation: ${prev.navigationType||'—'}
resident: ${bbResidentText(prev.resident)}
work canvases: ${prev.workCanvases||prev.rtCanvas||'—'} · memory: ${prev.memory||'N/A'}`:'no previous snapshot'}

LAST EVENTS
${tail||'—'}`;}
  function writeDiag(stage,extra={}){if(!DIAG)return;if(BLACKBOX&&stage==='diagnostic-start'){bbPrevious=null;bbEvents=[];bbBenchmarkDoneWall=0;bbMaxGap=0;bbLastBeat=performance.now();bbOrderlyExit=false;writeLocal(BB_JOURNAL_KEY,bbEvents)}bbStage=stage;if(BLACKBOX&&stage==='diagnostic-results-rendered')bbBenchmarkDoneWall=Date.now();try{sessionStorage.setItem(DIAG_KEY,JSON.stringify({stage,at:new Date().toISOString(),orderlyExit:false,...extra}))}catch(_){}showDiag(`Diagnostic · current stage: ${stage}`);bbJournal('stage:'+stage,extra);renderBlackbox()}
  function markDiagExit(){if(!DIAG)return;bbOrderlyExit=true;bbLastLifecycle='pagehide';bbJournal('pagehide');try{const prev=readDiag()||{};sessionStorage.setItem(DIAG_KEY,JSON.stringify({...prev,orderlyExit:true,exitAt:new Date().toISOString()}))}catch(_){}if(BLACKBOX)writeLocal(BB_KEY,bbSnapshot())}
  window.addEventListener('pagehide',markDiagExit);
  const state={image:null,running:false,benchmarking:false,tinyBuffer:null,tinySession:null,tinyProvider:'',tinyDownloadMs:NaN,tinyInitMs:NaN,tinyCacheState:'',tinySource:'',yoloBuffer:null,yoloSession:null,yoloProvider:'',yoloDownloadMs:NaN,yoloInitMs:NaN,yoloCacheState:'',yoloSource:'',rtPipe:null,rtBackend:'',rtDtype:'',rtLoadMs:NaN,rtCacheState:'',rtModule:null,lastHeadMaps:null,lastRun:{tiny:null,ssd:null,yolo:null,rt:null}};
  if(DIAG){const previous=readDiag(),diagButton=$('race-benchmark-diag'),disposeButton=$('race-dispose-diag');if(diagButton)diagButton.hidden=false;if(disposeButton)disposeButton.hidden=false;if(previous)showDiag(`Diagnostic · previous stage: ${previous.stage||'unknown'} · orderly pagehide: ${previous.orderlyExit?'yes':'no'}`);else showDiag('Diagnostic mode ready · no previous breadcrumb.');try{sessionStorage.setItem(DIAG_KEY,JSON.stringify({stage:'page-ready',at:new Date().toISOString(),orderlyExit:false}))}catch(_){}}
  if(BLACKBOX){bbPrevious=readLocal(BB_KEY);bbEvents=readLocal(BB_JOURNAL_KEY,[]);bbJournal('page-init',{navigation:bbNavType()});renderBlackbox();window.addEventListener('pageshow',()=>{bbLastLifecycle='pageshow';bbJournal('pageshow');renderBlackbox()});window.addEventListener('beforeunload',()=>{bbLastLifecycle='beforeunload';bbJournal('beforeunload');writeLocal(BB_KEY,bbSnapshot())});document.addEventListener('visibilitychange',()=>{bbLastLifecycle='visibility:'+document.visibilityState;bbJournal(bbLastLifecycle);writeLocal(BB_KEY,bbSnapshot());renderBlackbox()});setInterval(()=>{const now=performance.now(),gap=Math.max(0,now-bbLastBeat-1000);bbLastBeat=now;if(gap>bbMaxGap)bbMaxGap=gap;if(gap>=1500)bbJournal('event-loop-gap',{ms:Math.round(gap)});writeLocal(BB_KEY,bbSnapshot());renderBlackbox()},1000)}
  const report=(model,event)=>api.reportRuntimeEvent?.(model,event);
  const ms=api.ms,threshold=()=>api.getConfidence(),retainThreshold=()=>api.getRetentionThreshold?api.getRetentionThreshold():0.1,syncConfidence=()=>{$('race-confidence').textContent=threshold().toFixed(2)};syncConfidence();$('confidence').addEventListener('input',()=>{syncConfidence();redrawRaceResults();});
  const setStatus=(text,kind='')=>{const el=$('race-status');el.textContent=text;el.className=`status ${kind}`.trim()},sourceDims=s=>api.sourceSize(s),sleepFrame=()=>new Promise(requestAnimationFrame),sleepMs=value=>new Promise(resolve=>setTimeout(resolve,value));
  const median=v=>{const a=[...v].sort((x,y)=>x-y),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2},percentile=(v,p)=>{const a=[...v].sort((x,y)=>x-y);return a[Math.max(0,Math.min(a.length-1,Math.ceil(p*a.length)-1))]},cv=v=>{const m=v.reduce((a,b)=>a+b,0)/v.length,q=v.reduce((s,x)=>s+(x-m)**2,0)/v.length;return m>0?Math.sqrt(q)/m*100:NaN};
  function updateProgress(prefix,info){const pct=Number.isFinite(info.percent)?Math.max(0,Math.min(100,info.percent)):null,bar=$(`${prefix}-progress-bar`),text=$(`${prefix}-progress-text`);if(bar)bar.style.width=pct===null?'18%':`${pct.toFixed(1)}%`;if(text){const loaded=loader.formatBytes(info.loaded),total=loader.formatBytes(info.total);text.textContent=pct===null?`${loaded} downloaded`:`${pct.toFixed(0)}% · ${loaded} / ${total}`}}
  loader.status(TINY).then(x=>$('race-tiny-cache').textContent=x.source?`${x.state} · ${x.source}`:x.state).catch(()=>{});
  function evictTinyRawBuffer(){state.tinyBuffer=null;loader.evictMemory(TINY)}
  async function getTinyBuffer(){if(state.tinyBuffer){report('tinyyolo',{type:'runtime',backend:state.tinyProvider,downloadMs:0,initMs:state.tinyInitMs,bytes:TINY.bytes,cacheState:'memory',source:state.tinySource});return state.tinyBuffer}const r=await loader.load(TINY,{onState:x=>{state.tinyCacheState=x.state;state.tinySource=x.source||state.tinySource;$('race-tiny-cache').textContent=x.source?`${x.state} · ${x.source}`:x.state;if(x.source)$('race-tiny-source').textContent=x.source;report('tinyyolo',{type:'cache',text:x.source?`${x.state} · ${x.source}`:x.state})},onProgress:x=>{updateProgress('race-tiny',x);report('tinyyolo',{type:'progress',info:x})}});state.tinyBuffer=r.buffer;state.tinyDownloadMs=r.downloadMs;state.tinyCacheState=r.cacheState;state.tinySource=r.source;$('race-tiny-source').textContent=r.source;$('race-tiny-cache').textContent=`${r.cacheState} · ${r.source}`;report('tinyyolo',{type:'runtime',backend:state.tinyProvider,downloadMs:r.downloadMs,bytes:r.buffer.byteLength,cacheState:r.cacheState,source:r.source});return r.buffer}
  async function createTinySession(force=''){if(state.tinySession&&(!force||state.tinyProvider===force)){report('tinyyolo',{type:'runtime',backend:state.tinyProvider,downloadMs:0,initMs:state.tinyInitMs,bytes:TINY.bytes,cacheState:'memory',source:state.tinySource});return state.tinySession;}const buffer=await getTinyBuffer(),providers=(force?[force]:TINY.executionProviders).filter(p=>p!=='webgpu'||navigator.gpu);let lastError;for(const provider of providers)try{setStatus(`Initializing Tiny YOLOv2 on ${provider.toUpperCase()}…`,'loading');const t=performance.now(),session=await ort.InferenceSession.create(buffer,{executionProviders:[provider],graphOptimizationLevel:'all'});state.tinyInitMs=performance.now()-t;if(state.tinySession&&state.tinySession!==session&&typeof state.tinySession.release==='function')try{await state.tinySession.release()}catch(_){}state.tinySession=session;state.tinyProvider=provider;evictTinyRawBuffer();$('race-tiny-backend').textContent=provider.toUpperCase();$('race-tiny-startup').textContent=`${ms(state.tinyDownloadMs)} / ${ms(state.tinyInitMs)}`;report('tinyyolo',{type:'runtime',backend:provider,downloadMs:state.tinyDownloadMs,initMs:state.tinyInitMs,bytes:TINY.bytes,cacheState:state.tinyCacheState,source:state.tinySource});return session}catch(err){lastError=err;console.warn('Tiny YOLOv2 provider failed',provider,err)}evictTinyRawBuffer();throw lastError||new Error('No compatible Tiny YOLOv2 execution provider.')}
  loader.status(YOLO).then(x=>$('race-yolo-cache').textContent=x.source?`${x.state} · ${x.source}`:x.state).catch(()=>{});
  function evictYoloRawBuffer(){state.yoloBuffer=null;loader.evictMemory(YOLO)}
  async function getYoloBuffer(){if(state.yoloBuffer){report('yolox',{type:'runtime',backend:state.yoloProvider,downloadMs:0,initMs:state.yoloInitMs,bytes:YOLO.bytes,cacheState:'memory',source:state.yoloSource});return state.yoloBuffer}const r=await loader.load(YOLO,{onState:x=>{state.yoloCacheState=x.state;state.yoloSource=x.source||state.yoloSource;$('race-yolo-cache').textContent=x.source?`${x.state} · ${x.source}`:x.state;if(x.source)$('race-yolo-source').textContent=x.source;report('yolox',{type:'cache',text:x.source?`${x.state} · ${x.source}`:x.state})},onProgress:x=>{updateProgress('race-yolo',x);report('yolox',{type:'progress',info:x})}});state.yoloBuffer=r.buffer;state.yoloDownloadMs=r.downloadMs;state.yoloCacheState=r.cacheState;state.yoloSource=r.source;$('race-yolo-source').textContent=r.source;$('race-yolo-cache').textContent=`${r.cacheState} · ${r.source}`;report('yolox',{type:'runtime',backend:state.yoloProvider,downloadMs:r.downloadMs,bytes:r.buffer.byteLength,cacheState:r.cacheState,source:r.source});return r.buffer}
  async function createYoloSession(force=''){if(state.yoloSession&&(!force||state.yoloProvider===force)){report('yolox',{type:'runtime',backend:state.yoloProvider,downloadMs:0,initMs:state.yoloInitMs,bytes:YOLO.bytes,cacheState:'memory',source:state.yoloSource});return state.yoloSession;}const buffer=await getYoloBuffer(),providers=(force?[force]:YOLO.executionProviders).filter(p=>p!=='webgpu'||navigator.gpu);let lastError;for(const provider of providers)try{setStatus(`Initializing YOLOX on ${provider.toUpperCase()}…`,'loading');const t=performance.now(),session=await ort.InferenceSession.create(buffer,{executionProviders:[provider],graphOptimizationLevel:'all'});state.yoloInitMs=performance.now()-t;if(state.yoloSession&&state.yoloSession!==session&&typeof state.yoloSession.release==='function')try{await state.yoloSession.release()}catch(_){}state.yoloSession=session;state.yoloProvider=provider;evictYoloRawBuffer();$('race-yolo-backend').textContent=provider.toUpperCase();$('race-yolo-startup').textContent=`${ms(state.yoloDownloadMs)} / ${ms(state.yoloInitMs)}`;report('yolox',{type:'runtime',backend:provider,downloadMs:state.yoloDownloadMs,initMs:state.yoloInitMs,bytes:YOLO.bytes,cacheState:state.yoloCacheState,source:state.yoloSource});return session}catch(err){lastError=err;console.warn('YOLOX provider failed',provider,err)}evictYoloRawBuffer();throw lastError||new Error('No compatible YOLOX execution provider.')}
  function prepareDisplay(source,canvas){const {w,h}=sourceDims(source),scale=Math.min(1,640/Math.max(w,h));canvas.width=Math.max(1,Math.round(w*scale));canvas.height=Math.max(1,Math.round(h*scale));canvas.getContext('2d').drawImage(source,0,0,canvas.width,canvas.height)}
  function prepareTiny(source,canvas){const {w,h}=sourceDims(source),size=TINY.input;if(!w||!h)throw new Error('Race image has no readable dimensions.');const work=$('race-tiny-work');work.width=size;work.height=size;const ctx=work.getContext('2d',{willReadFrequently:true});ctx.drawImage(source,0,0,size,size);const rgba=ctx.getImageData(0,0,size,size).data,plane=size*size,chw=new Float32Array(plane*3);for(let p=0,s=0;p<plane;p++,s+=4){chw[p]=rgba[s];chw[plane+p]=rgba[s+1];chw[plane*2+p]=rgba[s+2]}prepareDisplay(source,canvas);return{tensor:new ort.Tensor('float32',chw,[1,3,size,size]),w,h}}
  async function runTinySession(session,tensor){const run=s=>s.run({[s.inputNames[0]]:tensor});try{return await run(session)}catch(err){if(state.tinyProvider!=='webgpu')throw err;console.warn('Tiny YOLOv2 WebGPU run failed; retrying WASM',err);const old=state.tinySession;state.tinySession=null;state.tinyProvider='';if(old&&typeof old.release==='function')try{await old.release()}catch(_){}return run(await createTinySession('wasm'))}}
  function prepareYolo(source,canvas){const {w,h}=sourceDims(source),size=YOLO.input;if(!w||!h)throw new Error('Race image has no readable dimensions.');const ratio=Math.min(size/h,size/w),rw=Math.max(1,Math.floor(w*ratio)),rh=Math.max(1,Math.floor(h*ratio)),work=$('race-yolo-work');work.width=size;work.height=size;const ctx=work.getContext('2d',{willReadFrequently:true});ctx.fillStyle='rgb(114,114,114)';ctx.fillRect(0,0,size,size);ctx.drawImage(source,0,0,rw,rh);const rgba=ctx.getImageData(0,0,size,size).data,plane=size*size,chw=new Float32Array(plane*3);for(let p=0,s=0;p<plane;p++,s+=4){chw[p]=rgba[s+2];chw[plane+p]=rgba[s+1];chw[plane*2+p]=rgba[s]}prepareDisplay(source,canvas);return{tensor:new ort.Tensor('float32',chw,[1,3,size,size]),ratio,w,h}}
  async function runYoloSession(session,tensor,{forceBackend='',allowFallback=true}={}){const run=s=>s.run({[s.inputNames[0]]:tensor});try{return await run(session)}catch(err){if(state.yoloProvider!=='webgpu'||!allowFallback||forceBackend)throw err;console.warn('YOLOX WebGPU run failed; retrying WASM',err);const old=state.yoloSession;state.yoloSession=null;state.yoloProvider='';if(old&&typeof old.release==='function')try{await old.release()}catch(_){}return run(await createYoloSession('wasm'))}}
  function iou(a,b){const t=Math.max(a[0],b[0]),l=Math.max(a[1],b[1]),bt=Math.min(a[2],b[2]),r=Math.min(a[3],b[3]),inter=Math.max(0,bt-t)*Math.max(0,r-l),aa=Math.max(0,a[2]-a[0])*Math.max(0,a[3]-a[1]),bb=Math.max(0,b[2]-b[0])*Math.max(0,b[3]-b[1]),u=aa+bb-inter;return u>0?inter/u:0}
  const sigmoid=x=>1/(1+Math.exp(-Math.max(-60,Math.min(60,x))));
  function decodeTiny(output){const data=output&&output.data;if(!data||data.length!==125*13*13)throw new Error(`Unexpected Tiny YOLOv2 output: ${data?data.length:0} values; expected ${125*13*13}.`);const grid=13,attrs=25,anchors=TINY.anchors,candidates=[],at=(channel,y,x)=>Number(data[(channel*grid+y)*grid+x]);for(let gy=0;gy<grid;gy++)for(let gx=0;gx<grid;gx++)for(let b=0;b<5;b++){const ch=b*attrs,tx=at(ch,gy,gx),ty=at(ch+1,gy,gx),tw=Math.max(-20,Math.min(20,at(ch+2,gy,gx))),th=Math.max(-20,Math.min(20,at(ch+3,gy,gx))),obj=sigmoid(at(ch+4,gy,gx));let maxLogit=-Infinity;for(let c=0;c<20;c++)maxLogit=Math.max(maxLogit,at(ch+5+c,gy,gx));let sum=0,best=-1,bestExp=-Infinity;for(let c=0;c<20;c++){const e=Math.exp(at(ch+5+c,gy,gx)-maxLogit);sum+=e;if(e>bestExp){bestExp=e;best=c}}const classProb=sum>0?bestExp/sum:0,score=obj*classProb;if(score<retainThreshold())continue;const cx=(gx+sigmoid(tx))/grid,cy=(gy+sigmoid(ty))/grid,bw=Math.exp(tw)*anchors[b*2]/grid,bh=Math.exp(th)*anchors[b*2+1]/grid,top=Math.max(0,cy-bh/2),left=Math.max(0,cx-bw/2),bottom=Math.min(1,cy+bh/2),right=Math.min(1,cx+bw/2);if(bottom>top&&right>left)candidates.push({score,classId:best,sourceLabel:VOC20[best],label:VOC_CANON[best],box:[top,left,bottom,right]})}candidates.sort((a,b)=>b.score-a.score);const kept=[];for(const d of candidates){if(kept.every(k=>k.label!==d.label||iou(d.box,k.box)<=TINY.nms))kept.push(d);if(kept.length>=100)break}return kept}
  async function runTiny(source,canvas){const session=await createTinySession(),ts=performance.now(),ps=performance.now(),prep=prepareTiny(source,canvas),preMs=performance.now()-ps,is=performance.now(),results=await runTinySession(session,prep.tensor),infMs=performance.now()-is,post=performance.now(),output=results[session.outputNames[0]]||results[Object.keys(results)[0]],detections=decodeTiny(output),visible=api.drawDetections(canvas,detections),postMs=performance.now()-post;return{preMs,infMs,postMs,totalMs:performance.now()-ts,detections,visible,width:TINY.input,height:TINY.input,retained:detections.length,retentionThreshold:retainThreshold(),timingBoundary:'onnx-run'}}
  function renderHeadMaps(maps){for(const head of maps){const canvas=$(`feature-s${head.stride}`);if(!canvas)continue;const ctx=canvas.getContext('2d'),img=ctx.createImageData(head.grid,head.grid);let max=0;for(const v of head.data)if(Number.isFinite(v)&&v>max)max=v;const d=max||1;for(let i=0;i<head.data.length;i++){const v=Math.max(0,Math.min(1,head.data[i]/d)),o=i*4;img.data[o]=Math.round(28+v*210);img.data[o+1]=Math.round(48+v*160);img.data[o+2]=Math.round(42+v*70);img.data[o+3]=255}const tiny=document.createElement('canvas');tiny.width=head.grid;tiny.height=head.grid;tiny.getContext('2d').putImageData(img,0,0);ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(tiny,0,0,canvas.width,canvas.height)}const s=$('feature-map-status');if(s)s.textContent='Live from last YOLOX inference'}
  function decodeYolo(output,ratio,w,h,renderFeatures=true){const data=output.data,attrs=85,expected=52*52+26*26+13*13,rows=Math.floor(data.length/attrs);if(rows!==expected)throw new Error(`Unexpected YOLOX output: ${rows} rows; expected ${expected}.`);const candidates=[],maps=[];let row=0;for(const stride of[8,16,32]){const grid=YOLO.input/stride,map=new Float32Array(grid*grid);let mi=0;for(let gy=0;gy<grid;gy++)for(let gx=0;gx<grid;gx++,row++,mi++){const o=row*attrs,obj=Number(data[o+4]);map[mi]=obj;let cls=0,cp=-Infinity;for(let c=0;c<80;c++){const p=Number(data[o+5+c]);if(p>cp){cp=p;cls=c}}const score=obj*cp;if(score<retainThreshold())continue;const cx=(Number(data[o])+gx)*stride,cy=(Number(data[o+1])+gy)*stride,bw=Math.exp(Number(data[o+2]))*stride,bh=Math.exp(Number(data[o+3]))*stride,x1=Math.max(0,(cx-bw/2)/ratio),y1=Math.max(0,(cy-bh/2)/ratio),x2=Math.min(w,(cx+bw/2)/ratio),y2=Math.min(h,(cy+bh/2)/ratio);if(x2>x1&&y2>y1)candidates.push({score,classId:cls,label:COCO80[cls],box:[y1/h,x1/w,y2/h,x2/w]})}maps.push({stride,grid,data:map})}candidates.sort((a,b)=>b.score-a.score);const kept=[];for(const d of candidates){if(kept.every(k=>iou(d.box,k.box)<=YOLO.nms))kept.push(d);if(kept.length>=100)break}state.lastHeadMaps=maps;if(renderFeatures&&!state.benchmarking)renderHeadMaps(maps);return kept}
  async function runYolo(source,canvas,{renderFeatures=true,forceBackend='',allowFallback=true}={}){const session=await createYoloSession(forceBackend),ts=performance.now(),ps=performance.now(),prep=prepareYolo(source,canvas),preMs=performance.now()-ps,is=performance.now(),results=await runYoloSession(session,prep.tensor,{forceBackend,allowFallback}),infMs=performance.now()-is,post=performance.now(),output=results[session.outputNames[0]]||results[Object.keys(results)[0]],detections=decodeYolo(output,prep.ratio,prep.w,prep.h,renderFeatures),visible=api.drawDetections(canvas,detections),postMs=performance.now()-post;return{preMs,infMs,postMs,totalMs:performance.now()-ts,detections,visible,width:YOLO.input,height:YOLO.input,retained:detections.length,retentionThreshold:retainThreshold()}}
  async function importTransformers(){if(state.rtModule)return state.rtModule;setStatus(`Loading pinned Transformers.js ${registry.runtime.transformersJs} runtime…`,'loading');state.rtModule=await import(registry.runtime.transformersJsUrl);state.rtModule.env.allowLocalModels=false;if('useWasmCache' in state.rtModule.env)state.rtModule.env.useWasmCache=true;return state.rtModule}
  async function rtCached(mod,device,dtype){try{if(mod.ModelRegistry&&typeof mod.ModelRegistry.is_pipeline_cached==='function')return await mod.ModelRegistry.is_pipeline_cached(RT.task,RT.modelId,{revision:RT.revision,device,dtype});if('caches'in window){for(const name of await caches.keys()){const cache=await caches.open(name),keys=await cache.keys();if(keys.some(r=>r.url.includes(RT.modelId)))return true}}}catch(_){}return false}
  function rtProgress(info){const bar=$('race-rt-progress-bar'),text=$('race-rt-progress-text');let pct=Number(info&&info.progress);if(Number.isFinite(pct)&&pct<=1)pct*=100;if(Number.isFinite(pct))bar.style.width=`${Math.max(0,Math.min(100,pct)).toFixed(1)}%`;const file=info&&info.file?String(info.file).split('/').pop():'model files',loaded=Number(info&&info.loaded),total=Number(info&&info.total);if(Number.isFinite(loaded)&&Number.isFinite(total)&&total>0)text.textContent=`${file} · ${(loaded/total*100).toFixed(0)}% · ${loader.formatBytes(loaded)} / ${loader.formatBytes(total)}`;else if(info&&info.status)text.textContent=`${info.status} · ${file}`;report('rtdetr',{type:'progress',info:{percent:Number.isFinite(pct)?pct:undefined,loaded,total}})}
  async function createRT(force=''){if(state.rtPipe&&(!force||state.rtBackend===force)){const cfg=RT.runtime[state.rtBackend]||{};report('rtdetr',{type:'runtime',backend:state.rtBackend,dtype:state.rtDtype,initMs:state.rtLoadMs,bytes:cfg.modelBytes,cacheState:'memory',source:`HF pinned ${RT.revision}`});return state.rtPipe;}const mod=await importTransformers(),attempts=force?[RT.runtime[force]]:(navigator.gpu?[RT.runtime.webgpu,RT.runtime.wasm]:[RT.runtime.wasm]);let lastError;for(const cfg of attempts)try{const cached=await rtCached(mod,cfg.device,cfg.dtype);$('race-rt-cache').textContent=cached?'browser cache':'network/cache miss';$('race-rt-backend').textContent=cfg.device.toUpperCase();$('race-rt-asset').textContent=`${cfg.dtype} · ~${loader.formatBytes(cfg.modelBytes)}`;setStatus(`Loading RT-DETR R18 on ${cfg.device.toUpperCase()} (${cfg.dtype})…`,'loading');const t=performance.now(),pipe=await mod.pipeline(RT.task,RT.modelId,{device:cfg.device,dtype:cfg.dtype,revision:RT.revision,progress_callback:rtProgress});state.rtLoadMs=performance.now()-t;state.rtPipe=pipe;state.rtBackend=cfg.device;state.rtDtype=cfg.dtype;state.rtCacheState=cached?'browser cache':'cached after load';$('race-rt-load').textContent=ms(state.rtLoadMs);$('race-rt-cache').textContent=state.rtCacheState;$('race-rt-progress-bar').style.width='100%';$('race-rt-progress-text').textContent='Ready';report('rtdetr',{type:'runtime',backend:cfg.device,dtype:cfg.dtype,initMs:state.rtLoadMs,bytes:cfg.modelBytes,cacheState:state.rtCacheState,source:`HF pinned ${RT.revision}`});return pipe}catch(err){lastError=err;console.warn('RT-DETR load attempt failed',cfg,err);state.rtPipe=null}throw lastError||new Error('RT-DETR could not be loaded.')}
  async function runRT(source,canvas,{forceBackend='',allowFallback=true}={}){
    let pipe=await createRT(forceBackend);
    const {w,h}=sourceDims(source),maxSide=RT.input||640,stageScale=Math.min(1,maxSide/Math.max(w,h)),stageW=Math.max(1,Math.round(w*stageScale)),stageH=Math.max(1,Math.round(h*stageScale)),work=$('race-rt-work');work.width=stageW;work.height=stageH;work.getContext('2d').drawImage(source,0,0,stageW,stageH);
    let output,infMs;
    try{const t=performance.now();output=await pipe(work,{threshold:retainThreshold()});infMs=performance.now()-t;}
    catch(err){
      if(state.rtBackend!=='webgpu'||!allowFallback||forceBackend)throw err;
      console.warn('RT-DETR WebGPU inference failed; retrying WASM q8',err);
      if(state.rtPipe&&typeof state.rtPipe.dispose==='function')try{await state.rtPipe.dispose()}catch(_){}
      state.rtPipe=null;state.rtBackend='';state.rtDtype='';
      pipe=await createRT('wasm');const t=performance.now();output=await pipe(work,{threshold:retainThreshold()});infMs=performance.now()-t;
    }
    const list=Array.isArray(output)&&Array.isArray(output[0])?output[0]:output,raw=Array.isArray(list)?list:[],clamp=v=>Math.max(0,Math.min(1,v));
    const detections=raw.map(x=>({score:Number(x.score),label:String(x.label),classId:-1,box:[Number(x.box?.ymin)/stageH,Number(x.box?.xmin)/stageW,Number(x.box?.ymax)/stageH,Number(x.box?.xmax)/stageW]})).filter(x=>Number.isFinite(x.score)&&x.box.every(Number.isFinite)).map(x=>({...x,box:x.box.map(clamp)})).filter(x=>x.box[2]>x.box[0]&&x.box[3]>x.box[1]);
    const droppedInvalid=raw.length-detections.length;prepareDisplay(source,canvas);const p=performance.now(),visible=api.drawDetections(canvas,detections),postMs=performance.now()-p;
    return{preMs:NaN,infMs,postMs,totalMs:infMs+postMs,detections,visible,width:RT.input,height:RT.input,timingBoundary:'transformers-pipeline',rawCount:raw.length,retained:detections.length,droppedInvalid,retentionThreshold:retainThreshold()};
  }
  async function releaseTinyRuntime(){const session=state.tinySession;state.tinySession=null;evictTinyRawBuffer();if(session&&typeof session.release==='function')try{await session.release()}catch(err){console.warn('Tiny YOLOv2 session release failed',err)}}
  async function releaseYoloRuntime(){const session=state.yoloSession;state.yoloSession=null;evictYoloRawBuffer();if(session&&typeof session.release==='function')try{await session.release()}catch(err){console.warn('YOLOX session release failed',err)}}
  async function releaseRTRuntime(){const pipe=state.rtPipe;state.rtPipe=null;if(pipe&&typeof pipe.dispose==='function')try{await pipe.dispose()}catch(err){console.warn('RT-DETR pipeline dispose failed',err)}}
  function getRaceSpecs(source,canvas,{benchmarking=false}={}){
    return[
      {key:'tinyyolo',prefix:'tiny',label:TINY.title,workCanvasId:'race-tiny-work',backend:()=>state.tinyProvider.toUpperCase(),run:()=>runTiny(source,canvas),release:releaseTinyRuntime},
      {key:'ssd',prefix:'ssd',label:registry.ssd.title,workCanvasId:'input-canvas',backend:()=>(api.getBaselineProvider()||'wasm').toUpperCase(),run:()=>api.runBaseline(source,canvas),release:async()=>{if(api.releaseBaselineRuntime)await api.releaseBaselineRuntime()}},
      {key:'yolox',prefix:'yolo',label:YOLO.title,workCanvasId:'race-yolo-work',backend:()=>state.yoloProvider.toUpperCase(),diagnosticBackends:[{value:'auto',label:'Auto'},{value:'webgpu',label:'WebGPU',available:()=>Boolean(navigator.gpu)},{value:'wasm',label:'WASM'}],run:options=>runYolo(source,canvas,{renderFeatures:!benchmarking,...(options||{})}),release:releaseYoloRuntime},
      {key:'rtdetr',prefix:'rt',label:RT.title,workCanvasId:'race-rt-work',backend:()=>state.rtBackend.toUpperCase()+' '+state.rtDtype,diagnosticBackends:[{value:'auto',label:'Auto'},{value:'webgpu',label:'WebGPU fp16',available:()=>Boolean(navigator.gpu)},{value:'wasm',label:'WASM q8'}],run:options=>runRT(source,canvas,options),release:releaseRTRuntime}
    ];
  }
  async function releaseRaceRuntimes(exceptKey=''){for(const spec of getRaceSpecs(null,null,{benchmarking:true})){if(spec.key===exceptKey)continue;if(spec.release)await spec.release();if(BLACKBOX)bbResident[spec.key]=false}}
  function getDiagnosticSelection(){
    const specs=getRaceSpecs(null,null,{benchmarking:true});
    if(!BLACKBOX)return specs.map(x=>x.key);
    const boxes=[...document.querySelectorAll('[data-diag-model]')];
    const keys=boxes.filter(x=>x.checked).map(x=>x.dataset.diagModel).filter(key=>specs.some(s=>s.key===key));
    writeLocal(BB_SELECTION_KEY,keys);
    return keys;
  }
  function getDiagnosticBackendSelection(){const out={};document.querySelectorAll('[data-diag-backend]').forEach(select=>{if(select.value&&select.value!=='auto')out[select.dataset.diagBackend]=select.value});writeLocal(BB_BACKEND_KEY,out);return out}
  async function copyBlackbox(){const el=$('race-diag-blackbox'),button=$('race-diag-copy');if(!el||!button)return;const text=el.textContent||'';let copied=false;try{if(navigator.clipboard&&typeof navigator.clipboard.writeText==='function'){await navigator.clipboard.writeText(text);copied=true}}catch(_){}if(!copied){const area=document.createElement('textarea');area.value=text;area.readOnly=true;area.style.cssText='position:fixed;left:-9999px;top:0;opacity:0';document.body.appendChild(area);area.focus();area.select();area.setSelectionRange(0,area.value.length);try{copied=document.execCommand('copy')}catch(_){}area.remove()}const originalText=button.textContent;button.textContent=copied?'Copied':'Copy failed';setTimeout(()=>{button.textContent=originalText},1200)}
  function saveMatrix(next){bbMatrix=next;writeLocal(BB_MATRIX_KEY,bbMatrix);updateMatrixControls();renderBlackbox()}
  function updateMatrixControls(){if(!BLACKBOX)return;const run=$('race-diag-matrix'),stop=$('race-diag-matrix-stop'),status=$('race-diag-matrix-status');if(!run||!stop||!status)return;const resumable=bbMatrix&&bbMatrix.active&&['ready','interrupted','stopped','error'].includes(bbMatrix.phase);run.textContent=resumable?'Resume backend matrix':'Run backend matrix A–D ×10';run.disabled=!state.image||state.benchmarking||matrixRunning;stop.disabled=!matrixRunning;status.textContent='Matrix: '+bbMatrixText(bbMatrix)}
  function applyMatrixCase(def){document.querySelectorAll('[data-diag-model]').forEach(x=>x.checked=true);const settle=$('race-diag-settle');bbSettleMs=0;if(settle)settle.value='0';writeLocal(BB_SETTLE_KEY,0);for(const [key,mode] of Object.entries(def.backends)){const select=document.querySelector(`[data-diag-backend="${key}"]`);if(!select||![...select.options].some(x=>x.value===mode))throw new Error(`Matrix ${def.id}: ${key} ${mode} backend is unavailable.`);select.value=mode}bbPlan=getDiagnosticSelection();bbBackendPlan=getDiagnosticBackendSelection();renderBlackbox()}
  function stopBackendMatrix(){if(!matrixRunning)return;matrixStopRequested=true;if(bbMatrix)saveMatrix({...bbMatrix,phase:'stopping'});setStatus('Backend matrix will stop after the current ×20 attempt.','loading')}
  async function runBackendMatrix(){if(!BLACKBOX||!state.image||state.benchmarking||matrixRunning)return;if(!navigator.gpu){setStatus('Backend matrix cases B–D require WebGPU on this device.','error');return}matrixRunning=true;matrixStopRequested=false;let current=bbMatrix;if(!current||!current.active||current.phase==='complete'){current={active:true,phase:'ready',caseIndex:0,completedInCase:0,currentAttempt:0,attemptsPerCase:MATRIX_ATTEMPTS,startedAt:new Date().toISOString()}}else current={...current,active:true,phase:'ready'};saveMatrix(current);try{while(bbMatrix&&bbMatrix.active&&bbMatrix.caseIndex<MATRIX_CASES.length){if(matrixStopRequested)break;const def=MATRIX_CASES[bbMatrix.caseIndex];applyMatrixCase(def);const attempt=(bbMatrix.completedInCase||0)+1;saveMatrix({...bbMatrix,phase:'running',currentCase:def.id,currentAttempt:attempt,lastStartedAt:new Date().toISOString()});setStatus(`Matrix ${def.id} · attempt ${attempt}/${bbMatrix.attemptsPerCase} · ${def.label}`,'loading');const ok=await benchmarkRace(true);if(!ok){saveMatrix({...bbMatrix,phase:'error',active:true,lastError:'benchmark-error'});break}const caseDone=attempt>=bbMatrix.attemptsPerCase,nextCaseIndex=caseDone?bbMatrix.caseIndex+1:bbMatrix.caseIndex,done=nextCaseIndex>=MATRIX_CASES.length;saveMatrix({...bbMatrix,active:!done,phase:done?'complete':'ready',caseIndex:nextCaseIndex,completedInCase:caseDone?0:attempt,currentAttempt:0,lastCompletedAt:new Date().toISOString(),lastError:''});if(done){setStatus('Backend matrix complete: A–D ×10 finished without process reload.');break}if(matrixStopRequested){saveMatrix({...bbMatrix,active:true,phase:'stopped'});break}await sleepFrame()}}finally{if(matrixStopRequested&&bbMatrix&&bbMatrix.active&&bbMatrix.phase!=='stopped')saveMatrix({...bbMatrix,phase:'stopped'});matrixRunning=false;matrixStopRequested=false;updateMatrixControls()}}
  function setupDiagnosticControls(){
    if(!BLACKBOX)return;
    const wrap=$('race-diag-controls'),models=$('race-diag-models'),backends=$('race-diag-backends'),settle=$('race-diag-settle'),copyRow=$('race-diag-copy-row'),copyButton=$('race-diag-copy'),matrixButton=$('race-diag-matrix'),matrixStop=$('race-diag-matrix-stop');
    if(!wrap||!models)return;
    const specs=getRaceSpecs(null,null,{benchmarking:true}),known=new Set(specs.map(x=>x.key)),saved=readLocal(BB_SELECTION_KEY,null),selected=Array.isArray(saved)?saved.filter(x=>known.has(x)):specs.map(x=>x.key),settleOptions=[0,250,1000,3000],savedSettle=Number(readLocal(BB_SETTLE_KEY,0)),savedBackends=readLocal(BB_BACKEND_KEY,{});
    bbSettleMs=settleOptions.includes(savedSettle)?savedSettle:0;if(settle){settle.value=String(bbSettleMs);settle.addEventListener('change',()=>{const next=Number(settle.value);bbSettleMs=settleOptions.includes(next)?next:0;writeLocal(BB_SETTLE_KEY,bbSettleMs);renderBlackbox()})}
    models.replaceChildren();
    for(const spec of specs){
      const label=document.createElement('label'),box=document.createElement('input'),text=document.createElement('span');
      label.style.cssText='display:inline-flex;align-items:center;gap:5px;margin:2px 10px 2px 0';
      box.type='checkbox';box.dataset.diagModel=spec.key;box.checked=selected.includes(spec.key);
      box.addEventListener('change',()=>{bbPlan=getDiagnosticSelection();renderBlackbox()});
      text.textContent=spec.label;label.append(box,text);models.appendChild(label);
    }
    if(backends){backends.replaceChildren();for(const spec of specs){if(!Array.isArray(spec.diagnosticBackends)||!spec.diagnosticBackends.length)continue;const label=document.createElement('label'),select=document.createElement('select'),text=document.createElement('span');label.style.cssText='display:inline-flex;align-items:center;gap:6px;margin:4px 12px 2px 0';select.dataset.diagBackend=spec.key;text.textContent=spec.label+' backend';for(const option of spec.diagnosticBackends){if(option.available&&!option.available())continue;const el=document.createElement('option');el.value=option.value;el.textContent=option.label;select.appendChild(el)}const savedMode=savedBackends&&savedBackends[spec.key];select.value=[...select.options].some(x=>x.value===savedMode)?savedMode:'auto';select.addEventListener('change',()=>{bbBackendPlan=getDiagnosticBackendSelection();renderBlackbox()});label.append(text,select);backends.appendChild(label)}}
    const setAll=checked=>{models.querySelectorAll('[data-diag-model]').forEach(x=>x.checked=checked);bbPlan=getDiagnosticSelection();renderBlackbox()};
    $('race-diag-all').addEventListener('click',()=>setAll(true));
    $('race-diag-none').addEventListener('click',()=>setAll(false));
    if(bbMatrix&&bbMatrix.active&&bbMatrix.phase==='running'){bbMatrix={...bbMatrix,phase:'interrupted',interruptedAt:new Date().toISOString()};writeLocal(BB_MATRIX_KEY,bbMatrix)}wrap.hidden=false;if(copyRow)copyRow.hidden=false;if(copyButton)copyButton.addEventListener('click',copyBlackbox);if(matrixButton)matrixButton.addEventListener('click',runBackendMatrix);if(matrixStop)matrixStop.addEventListener('click',stopBackendMatrix);bbPlan=getDiagnosticSelection();bbBackendPlan=getDiagnosticBackendSelection();for(const spec of specs)if(!(spec.key in bbResident))bbResident[spec.key]=false;updateMatrixControls();renderBlackbox();
  }
  function setDiagnosticControlsDisabled(disabled){if(!BLACKBOX)return;document.querySelectorAll('[data-diag-model],[data-diag-backend]').forEach(x=>x.disabled=disabled);$('race-diag-all').disabled=disabled;$('race-diag-none').disabled=disabled;const settle=$('race-diag-settle');if(settle)settle.disabled=disabled;updateMatrixControls()}
  const visible=d=>d.filter(x=>x.score>=threshold());
  function compare(a,b){const aa=visible(a),bb=visible(b),used=new Set();let both=0;for(const old of aa){let best=-1,bi=0;for(let i=0;i<bb.length;i++){if(used.has(i)||bb[i].label!==old.label)continue;const v=iou(old.box,bb[i].box);if(v>=.35&&v>bi){best=i;bi=v}}if(best>=0){used.add(best);both++}}return{both,aOnly:aa.length-both,bOnly:bb.length-both}}
  function hasMatch(det,list){return list.some(other=>other.label===det.label&&iou(det.box,other.box)>=.35)}
  function updateOverlap(){const t=state.lastRun.tiny?.detections,s=state.lastRun.ssd?.detections,y=state.lastRun.yolo?.detections,r=state.lastRun.rt?.detections;if(!t||!s||!y||!r)return;const tv=visible(t),sv=visible(s),yv=visible(y),rv=visible(r);$('race-match-tiny-ssd').textContent=String(compare(t,s).both);$('race-match-tiny-yolo').textContent=String(compare(t,y).both);$('race-match-tiny-rt').textContent=String(compare(t,r).both);$('race-match-ssd-yolo').textContent=String(compare(s,y).both);$('race-match-ssd-rt').textContent=String(compare(s,r).both);$('race-match-yolo-rt').textContent=String(compare(y,r).both);$('race-only-tiny').textContent=String(tv.filter(d=>!hasMatch(d,sv)&&!hasMatch(d,yv)&&!hasMatch(d,rv)).length);$('race-only-ssd').textContent=String(sv.filter(d=>!hasMatch(d,tv)&&!hasMatch(d,yv)&&!hasMatch(d,rv)).length);$('race-only-yolo').textContent=String(yv.filter(d=>!hasMatch(d,tv)&&!hasMatch(d,sv)&&!hasMatch(d,rv)).length);$('race-only-rt').textContent=String(rv.filter(d=>!hasMatch(d,tv)&&!hasMatch(d,sv)&&!hasMatch(d,yv)).length);}
  function redrawRaceResults(){if(!state.image||state.running||state.benchmarking)return;let redrawn=false;for(const pair of [['tiny','tiny'],['ssd','ssd'],['yolo','yolo'],['rt','rt']]){const key=pair[0],slot=pair[1],run=state.lastRun[key];if(!run)continue;const canvas=$('race-'+slot+'-canvas');prepareDisplay(state.image,canvas);run.visible=api.drawDetections(canvas,run.detections);$('race-'+slot+'-count').textContent=String(run.visible);redrawn=true}if(redrawn){updateOverlap();setStatus('Confidence '+threshold().toFixed(2)+' applied to retained race outputs without new inference.')}}
  function useImage(img,label){state.image=img;state.lastRun={tiny:null,ssd:null,yolo:null,rt:null};$('race-run').disabled=false;$('race-benchmark').disabled=true;if(DIAG){$('race-benchmark-diag').disabled=false;$('race-dispose-diag').disabled=true;}for(const k of['tiny','ssd','yolo','rt']){$('race-'+k+'-empty').hidden=false;$('race-'+k+'-canvas').hidden=true}for(const id of['race-tiny-inf','race-tiny-total','race-tiny-count','race-ssd-inf','race-ssd-total','race-ssd-count','race-yolo-inf','race-yolo-total','race-yolo-count','race-rt-inf','race-rt-total','race-rt-count','race-rt-retained','race-rt-invalid','race-match-tiny-ssd','race-match-tiny-yolo','race-match-tiny-rt','race-match-ssd-yolo','race-match-ssd-rt','race-match-yolo-rt','race-only-tiny','race-only-ssd','race-only-yolo','race-only-rt','rb-tiny-backend','rb-tiny-p50','rb-tiny-p90','rb-tiny-total','rb-tiny-cv','rb-ssd-backend','rb-ssd-p50','rb-ssd-p90','rb-ssd-total','rb-ssd-cv','rb-yolo-backend','rb-yolo-p50','rb-yolo-p90','rb-yolo-total','rb-yolo-cv','rb-rt-backend','rb-rt-p50','rb-rt-p90','rb-rt-total','rb-rt-cv'])$(id).textContent='—';$('race-ssd-input').textContent='dynamic ≤640';$('race-benchmark-note').textContent='Not benchmarked yet.';setStatus(label+' ready. Run four generations with confidence '+threshold().toFixed(2)+'.');updateMatrixControls()}
  $('race-image-file').addEventListener('change',e=>{const file=e.target.files&&e.target.files[0];if(!file)return;if(!file.type.startsWith('image/')){setStatus('Please choose an image file.','error');return}const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{URL.revokeObjectURL(url);useImage(img,file.name||'Race image')};img.onerror=()=>{URL.revokeObjectURL(url);setStatus('The selected race image could not be decoded.','error')};img.src=url});
  $('race-use-current').addEventListener('click',()=>{const img=api.getImage();if(!img){setStatus('No Time Machine image is loaded yet.','error');return}useImage(img,'Time Machine image')});
  async function runRace(){if(!state.image||state.running)return;state.running=true;const image=state.image;$('race-image-file').disabled=true;$('confidence').disabled=true;$('race-run').disabled=true;$('race-benchmark').disabled=true;$('race-use-current').disabled=true;syncConfidence();try{
    setStatus('Running Tiny YOLOv2 (2016)… first load is ~63.5 MB.','loading');const tiny=await runTiny(image,$('race-tiny-canvas'));state.lastRun.tiny=tiny;$('race-tiny-empty').hidden=true;$('race-tiny-canvas').hidden=false;$('race-tiny-inf').textContent=ms(tiny.infMs);$('race-tiny-total').textContent=ms(tiny.totalMs);$('race-tiny-count').textContent=String(tiny.visible);
    setStatus('Running SSD-MobileNet baseline…','loading');const ssd=await api.runBaseline(image,$('race-ssd-canvas'));state.lastRun.ssd=ssd;$('race-ssd-empty').hidden=true;$('race-ssd-canvas').hidden=false;$('race-ssd-backend').textContent=(api.getBaselineProvider()||'WASM').toUpperCase();$('race-ssd-input').textContent=ssd.width+'×'+ssd.height;$('race-ssd-inf').textContent=ms(ssd.infMs);$('race-ssd-total').textContent=ms(ssd.totalMs);$('race-ssd-count').textContent=String(ssd.visible);
    setStatus('Running YOLOX-Nano…','loading');const yolo=await runYolo(image,$('race-yolo-canvas'));state.lastRun.yolo=yolo;$('race-yolo-empty').hidden=true;$('race-yolo-canvas').hidden=false;$('race-yolo-inf').textContent=ms(yolo.infMs);$('race-yolo-total').textContent=ms(yolo.totalMs);$('race-yolo-count').textContent=String(yolo.visible);
    setStatus('Running RT-DETR R18… first load may download 20–40 MB.','loading');const rt=await runRT(image,$('race-rt-canvas'));state.lastRun.rt=rt;$('race-rt-empty').hidden=true;$('race-rt-canvas').hidden=false;$('race-rt-inf').textContent=ms(rt.infMs);$('race-rt-total').textContent=ms(rt.totalMs);$('race-rt-count').textContent=String(rt.visible);$('race-rt-retained').textContent=rt.retained+' @ ≥'+rt.retentionThreshold.toFixed(2);$('race-rt-invalid').textContent=String(rt.droppedInvalid);
    updateOverlap();setStatus('Race complete: Tiny YOLOv2 '+tiny.visible+', SSD '+ssd.visible+', YOLOX '+yolo.visible+', RT-DETR '+rt.visible+'. Pairwise overlap is shown below.');$('race-benchmark').disabled=false;if(DIAG)$('race-benchmark-diag').disabled=false;
  }catch(err){console.error(err);setStatus(err&&err.message?err.message:String(err),'error')}finally{state.running=false;$('race-image-file').disabled=false;$('confidence').disabled=false;$('race-run').disabled=!state.image;$('race-use-current').disabled=false}}
  $('race-run').addEventListener('click',runRace);
  async function runModel(model,source,canvas,{benchmarking=false}={}){const spec=getRaceSpecs(source,canvas,{benchmarking}).find(x=>x.key===model);if(!spec)throw new Error(`Unknown runnable model: ${model}`);return spec.run()}
  function getRuntimeInfo(model){if(model==='tinyyolo')return{backend:state.tinyProvider,downloadMs:state.tinyDownloadMs,initMs:state.tinyInitMs,bytes:TINY.bytes,cacheState:state.tinyCacheState,source:state.tinySource};if(model==='ssd')return{backend:api.getBaselineProvider()||'wasm'};if(model==='yolox')return{backend:state.yoloProvider,downloadMs:state.yoloDownloadMs,initMs:state.yoloInitMs,bytes:YOLO.bytes,cacheState:state.yoloCacheState,source:state.yoloSource};if(model==='rtdetr'){const cfg=RT.runtime[state.rtBackend]||{};return{backend:state.rtBackend,dtype:state.rtDtype,initMs:state.rtLoadMs,bytes:cfg.modelBytes,cacheState:state.rtCacheState,source:`HF pinned ${RT.revision}`}}return{}}
  function setBench(prefix,backend,samples){const root=$(`rb-${prefix}-backend`);if(!root)return;const inf=samples.map(x=>x.infMs),tot=samples.map(x=>x.totalMs);root.textContent=backend;$(`rb-${prefix}-p50`).textContent=ms(median(inf));$(`rb-${prefix}-p90`).textContent=ms(percentile(inf,.9));$(`rb-${prefix}-total`).textContent=ms(median(tot));$(`rb-${prefix}-cv`).textContent=`${cv(inf).toFixed(1)}%`}
  async function benchmarkRace(diagnostic=false){
    if(!state.image||state.benchmarking)return;
    const image=state.image,hidden=document.createElement('canvas'),allSpecs=getRaceSpecs(image,hidden,{benchmarking:true}),selectedKeys=diagnostic?getDiagnosticSelection():allSpecs.map(x=>x.key),specs=allSpecs.filter(x=>selectedKeys.includes(x.key));
    if(!specs.length){setStatus('Select at least one diagnostic model.','error');return}
    const keepKey=diagnostic?specs[specs.length-1].key:'',runs=20,settleMs=diagnostic?bbSettleMs:0,backendPlan=diagnostic?{...bbBackendPlan}:{};let keptResident=false,benchmarkSucceeded=false;
    state.benchmarking=true;bbPlan=specs.map(x=>x.key);
    $('race-image-file').disabled=true;$('race-use-current').disabled=true;$('confidence').disabled=true;$('race-benchmark').disabled=true;$('race-run').disabled=true;
    if(DIAG){$('race-benchmark-diag').disabled=true;$('race-dispose-diag').disabled=true}
    if(diagnostic){bbAttempt+=1;writeLocal(BB_ATTEMPT_KEY,bbAttempt);setDiagnosticControlsDisabled(true);writeDiag('diagnostic-start',{attempt:bbAttempt,plan:[...bbPlan],keepResident:keepKey,settleMs,backendPlan})}
    try{
      await releaseRaceRuntimes();
      if(diagnostic)writeDiag('pre-benchmark-cleanup-complete',{plan:[...bbPlan],settleMs,backendPlan});
      for(let specIndex=0;specIndex<specs.length;specIndex++){
        const spec=specs[specIndex],samples=[],requestedBackend=backendPlan[spec.key]||'auto',runOptions=requestedBackend==='auto'?{}:{forceBackend:requestedBackend,allowFallback:false};
        try{
          if(diagnostic)writeDiag(spec.key+'-start');
          $('race-benchmark-note').textContent=spec.label+': warm-up…';
          await spec.run(runOptions);if(BLACKBOX)bbResident[spec.key]=true;
          if(diagnostic)writeDiag(spec.key+'-warmup-complete');
          await sleepFrame();
          for(let i=0;i<runs;i++){
            const runNo=i+1,traceRun=diagnostic&&spec.key===keepKey;
            $('race-benchmark-note').textContent=spec.label+': '+runNo+'/'+runs+' warm runs…';
            if(traceRun)writeDiag(spec.key+'-run-'+runNo+'-start',{run:runNo,runs});
            const result=await spec.run(runOptions);samples.push({infMs:result.infMs,totalMs:result.totalMs});
            if(traceRun)writeDiag(spec.key+'-run-'+runNo+'-complete',{run:runNo,runs});
            await sleepFrame();
          }
          setBench(spec.prefix,spec.backend(),samples);
          if(diagnostic)writeDiag(spec.key+'-20-complete');
        }finally{
          if(diagnostic&&spec.key===keepKey){
            keptResident=true;writeDiag(spec.key+'-dispose-skipped',{keptResident:true});
          }else if(spec.release){
            if(diagnostic)writeDiag(spec.key+'-dispose-start');
            await spec.release();if(BLACKBOX)bbResident[spec.key]=false;
            if(diagnostic)writeDiag(spec.key+'-dispose-complete');
          }
          hidden.width=1;hidden.height=1;await sleepFrame();
          if(diagnostic&&settleMs>0&&specIndex<specs.length-1){writeDiag(spec.key+'-settle-start',{settleMs});await sleepMs(settleMs);await sleepFrame();writeDiag(spec.key+'-settle-complete',{settleMs})}
        }
      }
      const kept=specs[specs.length-1];
      $('race-benchmark-note').textContent=diagnostic?`Diagnostic complete: ${kept.label} intentionally remains resident. Wait 30 seconds; use “Dispose resident” only for a separate disposal probe.`:'20 sequential warm runs per model complete. Source image and UI confidence were locked. Only one model runtime was kept resident at a time; startup remains excluded. RT-DETR p50/p90 measures its Transformers.js object-detection pipeline call; Tiny YOLOv2/SSD/YOLOX isolate ORT model execution.';
      setStatus(diagnostic?`Diagnostic ×20 complete · plan: ${specs.map(x=>x.label).join(' → ')} · ${kept.label} resident.`:'Four-generation warm benchmark complete.');
      if(diagnostic){writeDiag('diagnostic-results-rendered',{plan:[...bbPlan],keptResident:keepKey});$('race-dispose-diag').disabled=false}benchmarkSucceeded=true
    }catch(err){
      console.error(err);if(diagnostic)writeDiag('diagnostic-error',{message:err&&err.message?err.message:String(err),plan:[...bbPlan]});
      $('race-benchmark-note').textContent='Benchmark failed: '+(err.message||err);setStatus(err.message||String(err),'error');
    }finally{
      if(diagnostic){writeDiag('diagnostic-finally-start',{keepResident:keptResident?keepKey:null});await releaseRaceRuntimes(keptResident?keepKey:'');writeDiag(keptResident?'diagnostic-finally-complete-'+keepKey+'-resident':'diagnostic-finally-complete-no-resident',{keepResident:keptResident?keepKey:null});setDiagnosticControlsDisabled(false)}
      else await releaseRaceRuntimes();
      hidden.width=1;hidden.height=1;state.benchmarking=false;$('race-image-file').disabled=false;$('race-use-current').disabled=false;$('confidence').disabled=false;$('race-benchmark').disabled=false;$('race-run').disabled=false;if(DIAG)$('race-benchmark-diag').disabled=false;updateMatrixControls();
    }
    return benchmarkSucceeded;
  }
  async function diagnosticDisposeResident(){if(!DIAG||state.benchmarking)return;writeDiag('manual-resident-dispose-start',{resident:{...bbResident}});$('race-dispose-diag').disabled=true;setStatus('Diagnostic: disposing resident race runtimes now…','loading');try{await releaseRaceRuntimes();writeDiag('manual-resident-dispose-complete');setStatus('Diagnostic: resident runtime disposal completed without reload.')}catch(err){writeDiag('manual-resident-dispose-error',{message:err&&err.message?err.message:String(err)});setStatus(err.message||String(err),'error')}}
  setupDiagnosticControls();
  $('race-benchmark').addEventListener('click',()=>benchmarkRace(false));
  $('race-benchmark-diag').addEventListener('click',()=>benchmarkRace(true));
  $('race-dispose-diag').addEventListener('click',diagnosticDisposeResident);
  window.VisionRace=Object.freeze({runRace,benchmarkRace,runModel,getRuntimeInfo,getHeadMaps:()=>state.lastHeadMaps,getRTBackend:()=>state.rtBackend});
})();