(() => {
  'use strict';
  const api=window.VisionLab,registry=window.VisionModels,loader=window.VisionModelLoader;
  if(!api||!registry||!loader||!window.ort)return;
  const $=id=>document.getElementById(id),YOLO=registry.yolox,RT=registry.rtdetr,COCO80=registry.labels.coco80;
  const state={image:null,running:false,benchmarking:false,yoloBuffer:null,yoloSession:null,yoloProvider:'',yoloDownloadMs:NaN,yoloInitMs:NaN,rtPipe:null,rtBackend:'',rtDtype:'',rtLoadMs:NaN,rtModule:null,lastHeadMaps:null,lastRun:{ssd:null,yolo:null,rt:null}};
  const ms=api.ms,threshold=()=>api.getConfidence(),syncConfidence=()=>{$('race-confidence').textContent=threshold().toFixed(2)};syncConfidence();$('confidence').addEventListener('input',syncConfidence);
  const setStatus=(text,kind='')=>{const el=$('race-status');el.textContent=text;el.className=`status ${kind}`.trim()},sourceDims=s=>api.sourceSize(s),sleepFrame=()=>new Promise(requestAnimationFrame);
  const median=v=>{const a=[...v].sort((x,y)=>x-y),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2},percentile=(v,p)=>{const a=[...v].sort((x,y)=>x-y);return a[Math.max(0,Math.min(a.length-1,Math.ceil(p*a.length)-1))]},cv=v=>{const m=v.reduce((a,b)=>a+b,0)/v.length,q=v.reduce((s,x)=>s+(x-m)**2,0)/v.length;return m>0?Math.sqrt(q)/m*100:NaN};
  function updateProgress(prefix,info){const pct=Number.isFinite(info.percent)?Math.max(0,Math.min(100,info.percent)):null,bar=$(`${prefix}-progress-bar`),text=$(`${prefix}-progress-text`);if(bar)bar.style.width=pct===null?'18%':`${pct.toFixed(1)}%`;if(text){const loaded=loader.formatBytes(info.loaded),total=loader.formatBytes(info.total);text.textContent=pct===null?`${loaded} downloaded`:`${pct.toFixed(0)}% · ${loaded} / ${total}`}}
  loader.status(YOLO).then(x=>$('race-yolo-cache').textContent=x.source?`${x.state} · ${x.source}`:x.state).catch(()=>{});
  async function getYoloBuffer(){if(state.yoloBuffer)return state.yoloBuffer;const r=await loader.load(YOLO,{onState:x=>{$('race-yolo-cache').textContent=x.source?`${x.state} · ${x.source}`:x.state;if(x.source)$('race-yolo-source').textContent=x.source},onProgress:x=>updateProgress('race-yolo',x)});state.yoloBuffer=r.buffer;state.yoloDownloadMs=r.downloadMs;$('race-yolo-source').textContent=r.source;$('race-yolo-cache').textContent=`${r.cacheState} · ${r.source}`;return r.buffer}
  async function createYoloSession(force=''){if(state.yoloSession&&(!force||state.yoloProvider===force))return state.yoloSession;const buffer=await getYoloBuffer(),providers=(force?[force]:YOLO.executionProviders).filter(p=>p!=='webgpu'||navigator.gpu);let lastError;for(const provider of providers)try{setStatus(`Initializing YOLOX on ${provider.toUpperCase()}…`,'loading');const t=performance.now(),session=await ort.InferenceSession.create(buffer,{executionProviders:[provider],graphOptimizationLevel:'all'});state.yoloInitMs=performance.now()-t;if(state.yoloSession&&state.yoloSession!==session&&typeof state.yoloSession.release==='function')try{await state.yoloSession.release()}catch(_){}state.yoloSession=session;state.yoloProvider=provider;$('race-yolo-backend').textContent=provider.toUpperCase();$('race-yolo-startup').textContent=`${ms(state.yoloDownloadMs)} / ${ms(state.yoloInitMs)}`;return session}catch(err){lastError=err;console.warn('YOLOX provider failed',provider,err)}throw lastError||new Error('No compatible YOLOX execution provider.')}
  function prepareDisplay(source,canvas){const {w,h}=sourceDims(source),scale=Math.min(1,640/Math.max(w,h));canvas.width=Math.max(1,Math.round(w*scale));canvas.height=Math.max(1,Math.round(h*scale));canvas.getContext('2d').drawImage(source,0,0,canvas.width,canvas.height)}
  function prepareYolo(source,canvas){const {w,h}=sourceDims(source),size=YOLO.input;if(!w||!h)throw new Error('Race image has no readable dimensions.');const ratio=Math.min(size/h,size/w),rw=Math.max(1,Math.floor(w*ratio)),rh=Math.max(1,Math.floor(h*ratio)),work=$('race-yolo-work');work.width=size;work.height=size;const ctx=work.getContext('2d',{willReadFrequently:true});ctx.fillStyle='rgb(114,114,114)';ctx.fillRect(0,0,size,size);ctx.drawImage(source,0,0,rw,rh);const rgba=ctx.getImageData(0,0,size,size).data,plane=size*size,chw=new Float32Array(plane*3);for(let p=0,s=0;p<plane;p++,s+=4){chw[p]=rgba[s+2];chw[plane+p]=rgba[s+1];chw[plane*2+p]=rgba[s]}prepareDisplay(source,canvas);return{tensor:new ort.Tensor('float32',chw,[1,3,size,size]),ratio,w,h}}
  async function runYoloSession(session,tensor){const run=s=>s.run({[s.inputNames[0]]:tensor});try{return await run(session)}catch(err){if(state.yoloProvider!=='webgpu')throw err;console.warn('YOLOX WebGPU run failed; retrying WASM',err);const old=state.yoloSession;state.yoloSession=null;state.yoloProvider='';if(old&&typeof old.release==='function')try{await old.release()}catch(_){}return run(await createYoloSession('wasm'))}}
  function iou(a,b){const t=Math.max(a[0],b[0]),l=Math.max(a[1],b[1]),bt=Math.min(a[2],b[2]),r=Math.min(a[3],b[3]),inter=Math.max(0,bt-t)*Math.max(0,r-l),aa=Math.max(0,a[2]-a[0])*Math.max(0,a[3]-a[1]),bb=Math.max(0,b[2]-b[0])*Math.max(0,b[3]-b[1]),u=aa+bb-inter;return u>0?inter/u:0}
  function renderHeadMaps(maps){for(const head of maps){const canvas=$(`feature-s${head.stride}`);if(!canvas)continue;const ctx=canvas.getContext('2d'),img=ctx.createImageData(head.grid,head.grid);let max=0;for(const v of head.data)if(Number.isFinite(v)&&v>max)max=v;const d=max||1;for(let i=0;i<head.data.length;i++){const v=Math.max(0,Math.min(1,head.data[i]/d)),o=i*4;img.data[o]=Math.round(28+v*210);img.data[o+1]=Math.round(48+v*160);img.data[o+2]=Math.round(42+v*70);img.data[o+3]=255}const tiny=document.createElement('canvas');tiny.width=head.grid;tiny.height=head.grid;tiny.getContext('2d').putImageData(img,0,0);ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(tiny,0,0,canvas.width,canvas.height)}const s=$('feature-map-status');if(s)s.textContent='Live from last YOLOX inference'}
  function decodeYolo(output,ratio,w,h){const data=output.data,attrs=85,expected=52*52+26*26+13*13,rows=Math.floor(data.length/attrs);if(rows!==expected)throw new Error(`Unexpected YOLOX output: ${rows} rows; expected ${expected}.`);const candidates=[],maps=[];let row=0;for(const stride of[8,16,32]){const grid=YOLO.input/stride,map=new Float32Array(grid*grid);let mi=0;for(let gy=0;gy<grid;gy++)for(let gx=0;gx<grid;gx++,row++,mi++){const o=row*attrs,obj=Number(data[o+4]);map[mi]=obj;let cls=0,cp=-Infinity;for(let c=0;c<80;c++){const p=Number(data[o+5+c]);if(p>cp){cp=p;cls=c}}const score=obj*cp;if(score<threshold())continue;const cx=(Number(data[o])+gx)*stride,cy=(Number(data[o+1])+gy)*stride,bw=Math.exp(Number(data[o+2]))*stride,bh=Math.exp(Number(data[o+3]))*stride,x1=Math.max(0,(cx-bw/2)/ratio),y1=Math.max(0,(cy-bh/2)/ratio),x2=Math.min(w,(cx+bw/2)/ratio),y2=Math.min(h,(cy+bh/2)/ratio);if(x2>x1&&y2>y1)candidates.push({score,classId:cls,label:COCO80[cls],box:[y1/h,x1/w,y2/h,x2/w]})}maps.push({stride,grid,data:map})}candidates.sort((a,b)=>b.score-a.score);const kept=[];for(const d of candidates){if(kept.every(k=>iou(d.box,k.box)<=YOLO.nms))kept.push(d);if(kept.length>=100)break}state.lastHeadMaps=maps;if(!state.benchmarking)renderHeadMaps(maps);return kept}
  async function runYolo(source,canvas){const session=await createYoloSession(),ts=performance.now(),ps=performance.now(),prep=prepareYolo(source,canvas),preMs=performance.now()-ps,is=performance.now(),results=await runYoloSession(session,prep.tensor),infMs=performance.now()-is,post=performance.now(),output=results[session.outputNames[0]]||results[Object.keys(results)[0]],detections=decodeYolo(output,prep.ratio,prep.w,prep.h),visible=api.drawDetections(canvas,detections),postMs=performance.now()-post;return{preMs,infMs,postMs,totalMs:performance.now()-ts,detections,visible,width:YOLO.input,height:YOLO.input}}
  async function importTransformers(){if(state.rtModule)return state.rtModule;setStatus('Loading pinned Transformers.js runtime…','loading');state.rtModule=await import(registry.runtime.transformersJsUrl);state.rtModule.env.allowLocalModels=false;state.rtModule.env.cacheKey='vision-evolution-transformers-v1';return state.rtModule}
  async function rtCached(mod,device,dtype){try{if(mod.ModelRegistry&&typeof mod.ModelRegistry.is_pipeline_cached==='function')return await mod.ModelRegistry.is_pipeline_cached(RT.task,RT.modelId,{revision:RT.revision,device,dtype});if('caches'in window){const cache=await caches.open('vision-evolution-transformers-v1'),keys=await cache.keys();return keys.some(r=>r.url.includes(RT.modelId))}}catch(_){}return false}
  function rtProgress(info){const bar=$('race-rt-progress-bar'),text=$('race-rt-progress-text');let pct=Number(info&&info.progress);if(Number.isFinite(pct)&&pct<=1)pct*=100;if(Number.isFinite(pct))bar.style.width=`${Math.max(0,Math.min(100,pct)).toFixed(1)}%`;const file=info&&info.file?String(info.file).split('/').pop():'model files',loaded=Number(info&&info.loaded),total=Number(info&&info.total);if(Number.isFinite(loaded)&&Number.isFinite(total)&&total>0)text.textContent=`${file} · ${(loaded/total*100).toFixed(0)}% · ${loader.formatBytes(loaded)} / ${loader.formatBytes(total)}`;else if(info&&info.status)text.textContent=`${info.status} · ${file}`}
  async function createRT(force=''){if(state.rtPipe&&(!force||state.rtBackend===force))return state.rtPipe;const mod=await importTransformers(),attempts=force?[RT.runtime[force]]:(navigator.gpu?[RT.runtime.webgpu,RT.runtime.wasm]:[RT.runtime.wasm]);let lastError;for(const cfg of attempts)try{const cached=await rtCached(mod,cfg.device,cfg.dtype);$('race-rt-cache').textContent=cached?'browser cache':'network/cache miss';$('race-rt-backend').textContent=cfg.device.toUpperCase();$('race-rt-asset').textContent=`${cfg.dtype} · ~${loader.formatBytes(cfg.modelBytes)}`;setStatus(`Loading RT-DETR R18 on ${cfg.device.toUpperCase()} (${cfg.dtype})…`,'loading');const t=performance.now(),pipe=await mod.pipeline(RT.task,RT.modelId,{device:cfg.device,dtype:cfg.dtype,revision:RT.revision,progress_callback:rtProgress});state.rtLoadMs=performance.now()-t;state.rtPipe=pipe;state.rtBackend=cfg.device;state.rtDtype=cfg.dtype;$('race-rt-load').textContent=ms(state.rtLoadMs);$('race-rt-cache').textContent=cached?'browser cache':'cached after load';$('race-rt-progress-bar').style.width='100%';$('race-rt-progress-text').textContent='Ready';return pipe}catch(err){lastError=err;console.warn('RT-DETR load attempt failed',cfg,err);state.rtPipe=null}throw lastError||new Error('RT-DETR could not be loaded.')}
  async function runRT(source,canvas){
    let pipe=await createRT();
    const {w,h}=sourceDims(source),work=$('race-rt-work');work.width=w;work.height=h;work.getContext('2d').drawImage(source,0,0,w,h);
    let output,infMs;
    try{const t=performance.now();output=await pipe(work,{threshold:threshold()});infMs=performance.now()-t;}
    catch(err){
      if(state.rtBackend!=='webgpu')throw err;
      console.warn('RT-DETR WebGPU inference failed; retrying WASM q8',err);
      if(state.rtPipe&&typeof state.rtPipe.dispose==='function')try{await state.rtPipe.dispose()}catch(_){}
      state.rtPipe=null;state.rtBackend='';state.rtDtype='';
      pipe=await createRT('wasm');const t=performance.now();output=await pipe(work,{threshold:threshold()});infMs=performance.now()-t;
    }
    const list=Array.isArray(output)&&Array.isArray(output[0])?output[0]:output;
    const detections=(list||[]).map(x=>({score:Number(x.score),label:String(x.label),classId:-1,box:[Number(x.box.ymin)/h,Number(x.box.xmin)/w,Number(x.box.ymax)/h,Number(x.box.xmax)/w]})).filter(x=>Number.isFinite(x.score));
    prepareDisplay(source,canvas);const p=performance.now(),visible=api.drawDetections(canvas,detections),postMs=performance.now()-p;
    return{preMs:0,infMs,postMs,totalMs:infMs+postMs,detections,visible,width:RT.input,height:RT.input};
  }
  const visible=d=>d.filter(x=>x.score>=threshold());
  function compare(a,b){const aa=visible(a),bb=visible(b),used=new Set();let both=0;for(const old of aa){let best=-1,bi=0;for(let i=0;i<bb.length;i++){if(used.has(i)||bb[i].label!==old.label)continue;const v=iou(old.box,bb[i].box);if(v>=.35&&v>bi){best=i;bi=v}}if(best>=0){used.add(best);both++}}return{both,aOnly:aa.length-both,bOnly:bb.length-both}}
  function useImage(img,label){state.image=img;$('race-run').disabled=false;$('race-benchmark').disabled=true;for(const k of['ssd','yolo','rt']){$(`race-${k}-empty`).hidden=false;$(`race-${k}-canvas`).hidden=true}setStatus(`${label} ready. Run three generations with confidence ${threshold().toFixed(2)}.`)}
  $('race-image-file').addEventListener('change',e=>{const file=e.target.files&&e.target.files[0];if(!file)return;if(!file.type.startsWith('image/')){setStatus('Please choose an image file.','error');return}const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{URL.revokeObjectURL(url);useImage(img,file.name||'Race image')};img.onerror=()=>{URL.revokeObjectURL(url);setStatus('The selected race image could not be decoded.','error')};img.src=url});
  $('race-use-current').addEventListener('click',()=>{const img=api.getImage();if(!img){setStatus('No Time Machine image is loaded yet.','error');return}useImage(img,'Time Machine image')});
  function openRaceFor(model){document.querySelector('.tab[data-tab="model-race"]')?.click();const img=api.getImage();if(img)useImage(img,'Time Machine image');else setStatus(`${model==='rtdetr'?'RT-DETR R18':'YOLOX-Nano'} selected. Choose a race image, then run.`);setTimeout(()=>document.querySelector(model==='rtdetr'?'.transformer-model':'.race-model:nth-of-type(2)')?.scrollIntoView({behavior:'smooth',block:'center'}),80)}
  document.querySelectorAll('[data-runnable-model]').forEach(b=>b.addEventListener('click',()=>{const model=b.dataset.runnableModel;document.querySelectorAll('.milestone').forEach(m=>m.classList.toggle('active',m===b));if(model==='ssd')document.getElementById('image-stage')?.scrollIntoView({behavior:'smooth',block:'center'});else openRaceFor(model)}));
  async function runRace(){if(!state.image||state.running)return;state.running=true;$('race-run').disabled=true;$('race-benchmark').disabled=true;$('race-use-current').disabled=true;syncConfidence();try{
    setStatus('Running SSD-MobileNet baseline…','loading');const ssd=await api.runBaseline(state.image,$('race-ssd-canvas'));state.lastRun.ssd=ssd;$('race-ssd-empty').hidden=true;$('race-ssd-canvas').hidden=false;$('race-ssd-backend').textContent=(api.getBaselineProvider()||'WASM').toUpperCase();$('race-ssd-input').textContent=`${ssd.width}×${ssd.height}`;$('race-ssd-inf').textContent=ms(ssd.infMs);$('race-ssd-total').textContent=ms(ssd.totalMs);$('race-ssd-count').textContent=String(ssd.visible);
    setStatus('Running YOLOX-Nano…','loading');const yolo=await runYolo(state.image,$('race-yolo-canvas'));state.lastRun.yolo=yolo;$('race-yolo-empty').hidden=true;$('race-yolo-canvas').hidden=false;$('race-yolo-inf').textContent=ms(yolo.infMs);$('race-yolo-total').textContent=ms(yolo.totalMs);$('race-yolo-count').textContent=String(yolo.visible);
    setStatus('Running RT-DETR R18… first load may download 20–40 MB.','loading');const rt=await runRT(state.image,$('race-rt-canvas'));state.lastRun.rt=rt;$('race-rt-empty').hidden=true;$('race-rt-canvas').hidden=false;$('race-rt-inf').textContent=ms(rt.infMs);$('race-rt-total').textContent=ms(rt.totalMs);$('race-rt-count').textContent=String(rt.visible);
    const d=compare(ssd.detections,yolo.detections);$('race-both').textContent=String(d.both);$('race-ssd-only').textContent=String(d.aOnly);$('race-yolo-only').textContent=String(d.bOnly);setStatus(`Race complete: SSD ${ssd.visible}, YOLOX ${yolo.visible}, RT-DETR ${rt.visible}. SSD↔YOLOX matches: ${d.both}.`);$('race-benchmark').disabled=false;
  }catch(err){console.error(err);setStatus(err&&err.message?err.message:String(err),'error')}finally{state.running=false;$('race-run').disabled=!state.image;$('race-use-current').disabled=false}}
  $('race-run').addEventListener('click',runRace);
  function setBench(prefix,backend,samples){const inf=samples.map(x=>x.infMs),tot=samples.map(x=>x.totalMs);$(`rb-${prefix}-backend`).textContent=backend;$(`rb-${prefix}-p50`).textContent=ms(median(inf));$(`rb-${prefix}-p90`).textContent=ms(percentile(inf,.9));$(`rb-${prefix}-total`).textContent=ms(median(tot));$(`rb-${prefix}-cv`).textContent=`${cv(inf).toFixed(1)}%`}
  async function benchmarkRace(){if(!state.image||state.benchmarking)return;state.benchmarking=true;$('race-benchmark').disabled=true;$('race-run').disabled=true;const runs=20,hidden=document.createElement('canvas');try{for(const spec of[
    {key:'ssd',label:'SSD-MobileNet',backend:()=>(api.getBaselineProvider()||'wasm').toUpperCase(),run:()=>api.runBaseline(state.image,hidden)},
    {key:'yolo',label:'YOLOX-Nano',backend:()=>state.yoloProvider.toUpperCase(),run:()=>runYolo(state.image,hidden)},
    {key:'rt',label:'RT-DETR R18',backend:()=>`${state.rtBackend.toUpperCase()} ${state.rtDtype}`,run:()=>runRT(state.image,hidden)}
  ]){const samples=[];for(let i=0;i<runs;i++){$('race-benchmark-note').textContent=`${spec.label}: ${i+1}/${runs} warm runs…`;samples.push(await spec.run());await sleepFrame()}setBench(spec.key,spec.backend(),samples)}$('race-benchmark-note').textContent='20 sequential warm runs per model complete. RT-DETR p50/p90 measures its Transformers.js object-detection pipeline call; SSD/YOLOX isolate ORT model execution.';setStatus('Three-generation warm benchmark complete.')}catch(err){console.error(err);$('race-benchmark-note').textContent=`Benchmark failed: ${err.message||err}`;setStatus(err.message||String(err),'error')}finally{state.benchmarking=false;$('race-benchmark').disabled=false;$('race-run').disabled=false}}
  $('race-benchmark').addEventListener('click',benchmarkRace);
  window.VisionRace=Object.freeze({runRace,benchmarkRace,getHeadMaps:()=>state.lastHeadMaps,getRTBackend:()=>state.rtBackend});
})();